### ISSUE TITLE
 blpop ResponseError: timeout is not an integer or out of range  

### ISSUE THREAD

**Issue by shanliu** [mitsuhiko/redis-rs#1060]
Is it compatible with <REDIS 6.0?

 cargo.toml:
redis = "~0.24";

**Comment by nihohit** [comment]
https://redis.io/commands/blpop/
`Starting with Redis version 6.0.0: timeout is interpreted as a double instead of an integer.`

If you're using earlier redis, you'll need to pass a value that will be parsed to an integer.

**Comment by nihohit** [comment]
I'm not sure what you mean here, since the choice of type is done at
compile time, but PRs are always welcome 🙂

**Comment by nihohit** [comment]
as I said, PRs are welcome.
