### ISSUE TITLE
PUBLISH command in pubsub

### ISSUE THREAD

**Issue by sinhpham** [mitsuhiko/redis-rs#107]
I'm surprised to see no PUBLISH command in http://mitsuhiko.github.io/redis-rs/redis/struct.PubSub.html. It would be nice to have one, as currently I have to use the low level API.

**Comment by badboy** [comment]
`publish` is a normal command, so it should Simon be implemented like other commands

**Comment by gkelly** [comment]
Sorry if I'm misunderstanding, but @badboy you're saying that there shouldn't be a dedicated publish command on PubSub?  Just trying to see if it's worth writing a patch for.  :)

**Comment by badboy** [comment]
*(I have no idea how I managed to add an `Simon` in the comment above)*

What I meant: `publish` should be implemented on the connection directly, just as other commands like `set`, `get`, etc.
You can't publish from a subscribed connection anyway.

**Comment by gkelly** [comment]
Understood.  Thanks!

**Comment by badboy** [comment]
All it takes is 4 lines, implemented in #109
