### ISSUE TITLE
Handling bulk mixed types?

### ISSUE THREAD

**Issue by frnsys** [mitsuhiko/redis-rs#112]
I'm working on porting the [redis-cluster library](https://github.com/antirez/redis-rb-cluster/blob/master/cluster.rb) to rust and it uses the [`CLUSTER SLOTS`](https://redis.io/commands/cluster-slots) command to initialize its slots cache. This returns a mixed nested array and I'm not sure how to properly handle it.

```
let mut cmd = Cmd::new();
cmd.arg("CLUSTER").arg("SLOTS");
```

If I try a nested vector of `u8`:

```
let res = cmd.query::<Vec<Vec<u8>>>(&conn);
```

I get `Ok([[171, 255], [0, 84], [85, 170]])`.

If I try a nested vector of `String` (`<Vec<Vec<String>>>`) I get `Ok([[], [], []])`.

If I try a double nested vector of `String` (`<Vec<Vec<String>>>`) I get `Ok([[["127.0.0.1"], ["127.0.0.1"]], [["127.0.0.1"], ["127.0.0.1"]], [["127.0.0.1"], ["127.0.0.1"]]])`.

Here's what the response is:

```
response was bulk(bulk(int(10923), int(16383), bulk(string-data('"127.0.0.1"'), int(7002)), bulk(string-data('"127.0.0.1"'), int(7005))), bulk(int(0), int(5460), bulk(string-data('"127.0.0.1"'), int(7000)), bulk(string-data('"127.0.0.1"'), int(7003))), bulk(int(5461), int(10922), bulk(string-data('"127.0.0.1"'), int(7001)), bulk(string-data('"127.0.0.1"'), int(7004))))
```

**Comment by badboy** [comment]
The parser currently just skips stuff it can't decode for nested things when trying to make it nested Vecs (as ints are not converted back to their binary/string representation).
You could try to convert it into tuples.

The type should be (untested):

```rust
Vec<(u16,u16, Vec<(String,u16)>)>
```

**Comment by frnsys** [comment]
thanks for the help, unfortunately I wasn't able to get that to work, but I ended up parsing the response manually.

**Comment by dvdplm** [comment]
@badboy your suggestion worked perfectly for my case. I have `bulk(bulk(int, int, int), int, int)` and used `Vec<(Vec<u64>, u64, u64)>`. Thanks! 👍 
Could perhaps be something to put in the docs? :)

**Comment by michael-grunder** [comment]
In case someone lands here looking for a solution to this, I've found a workaround.  The potential solution of using Tuples looks like it _should_ work, but I was not able to get any combination to work.

What can work (without resorting to manual RESP parsing) is using LUA to "squish" the output of cluster slots:

```rust
const LUA: &'static str = "
local slots = redis.call('CLUSTER','SLOTS')
local sslot, eslot, host, port, info, hash, line
local resp = {}
local node

for i=1,#slots do
    resp[#resp+1] = slots[i][1]
    resp[#resp+1] = slots[i][2]

    node = {}
    for j=3, #slots[i] do
        node[#node+1] = slots[i][j][1]
        node[#node+1] = slots[i][j][2]
        node[#node+1] = slots[i][j][3]
    end
    resp[#resp+1] = node
end

return resp
";
```

Then, redis-rs can deserialize into a vector of the following structure:

```rust
type LuaSlot = (u16, u16, Vec<(String, u16, String)>);
```

Call like so:

```rust
    let r: Vec<LuaSlot> = cmd.arg("EVAL").arg(LUA).arg(0).query(con).unwrap();
    println!("{:#?}", r);
```
