### ISSUE TITLE
No bindings for LSET

### ISSUE THREAD

**Issue by lynn** [mitsuhiko/redis-rs#115]
There don’t seem to be command bindings for [`LSET`](https://redis.io/commands/lset). You have to write:

    cmd("LSET").arg(key).arg(index).arg(value)

Is there any reason for this omission?

**Comment by badboy** [comment]
No reason other than no one implemented it yet. Feel free to submit a pull request

**Comment by michael-grunder** [comment]
I think #121 should do it.
