### ISSUE TITLE
Add support for GEO commands

### ISSUE THREAD

**Issue by categulario** [mitsuhiko/redis-rs#131]
As of redis 3.2 we have GEOADD, GEOPOS, GEORADIUS... It would be great for them to ve available here

**Comment by categulario** [comment]
Can I try to add them? it seems easy given the `commands.rs` file.

**Comment by badboy** [comment]
They are implemented in #130, aren't they? I just need to review and merge that.

**Comment by categulario** [comment]
true, I'll close this issue
