### ISSUE TITLE
Additional collaborators?

### ISSUE THREAD

**Issue by jwilm** [mitsuhiko/redis-rs#137]
Hey everyone,

It seems like velocity has slowed down on this project in recent months. Completely understandably, current maintainers are presumably busy with other projects/life/etc. I'm not here to critique. Rather, I am curious if the project would be open to additional maintainers to keep PRs/issues advancing and getting bug fixes and patches shipped.

To that end, I'm willing to volunteer some of my own time. I'm also open to other solutions if the project prefers not to add more maintainers. At the very least, let's start a dialog about it.

**Comment by jwilm** [comment]
cc @mitsuhiko, I just realized you might not have seen this since you're not "Watching" the project.

**Comment by mitsuhiko** [comment]
I would love to get more people on the project that can help out :) Can I add you as a maintainer?

**Comment by jwilm** [comment]
Yes, I would be happy to help. Finding another maintainer in addition to myself would be beneficial so that code review can happen even when you and @badboy are unavailable. I would also like to be able to pull you in as needed to comment on high level design decisions.

**Comment by mitsuhiko** [comment]
Sent you an invite.

**Comment by badboy** [comment]
@jwilm Welcome onboard! Good to see people getting involved.

**Comment by Marwes** [comment]
If there is anything I can do to help get PRs merged and deployed I'd be happy to help (though some of those PRs are mine).
