### ISSUE TITLE
Tests are flakey

### ISSUE THREAD

**Issue by jwilm** [mitsuhiko/redis-rs#138]
In trying to figure out why tests are failing on #136, I've found that there's a race condition with server setup that leads to an error like "Connection reset by peer" or __. The connection reset by peer error happens when the client connects to the plain TCP socket we listen on in order to acquire an unused port and the socket is subsequently closed. Although the connection is already dropped in the test setup code, the kernel doesn't necessarily clean up connections immediately.

Additionally, starting the Redis server doesn't always work. Again, this is because the kernel doesn't clean up sockets synchronously. I added locking around the server setup to ensure this wasn't simply an issue with port collision. Logging I added shows the following:

```
STDOUT
======
31115:M 01 Nov 11:24:09.594 # Creating Server TCP listening socket 127.0.0.1:35061: bind: Address already in use
```

I think the easiest solution here is having a singleton Redis server in the tests. This would also make it trivial for developers to provide an already running Redis instance in case the `redis-server` binary isn't on the current `PATH`.

Alternatively, we could enter a retry loop when setting up each Redis instance and check that the server actually responds appropriately to a command like `PING`. I prefer the former solution since it's simple and the tests don't actually take that long to run in series.

**Comment by jwilm** [comment]
@mitsuhiko @badboy any feedback on this? I'm basically proposing to serialize the tests due to network race conditions and Redis not supporting a bind port of 0 (assign random open port).

**Comment by badboy** [comment]
We once had them run with `RUST_TEST_THREADS=1`, e.g. serialized and I was happy that we don't need that anymore.
Then again trying to hack around this will always end hacky (we do the same for redis-rb and it's a mess)
