### ISSUE TITLE
redis connection string caveat:  username is required for url crate to recognize passwd

### ISSUE THREAD

**Issue by Dowwie** [mitsuhiko/redis-rs#144]
fyi-- a username needs to be passed into the dburl connection string in order for the url crate to recognize the password.  Redis only needs a password so "_" suffices for the username.

I've raised an issue with the url crate project to try to get an update for optional username support in the string:  https://github.com/servo/rust-url/issues/440

For the meanwhile, redis-rs documentation should at least address this caveat.

**Comment by badboy** [comment]
`rust-url` is working just fine. The URL format is: `protocol://[user]:[password]@host[:port]`.
This means the password is _always_ after a colon (`:`). An empty user field is allowed.
Therefore `redis://:password@localhost:6379` works just fine.
That's also clearly documented in the [Connection parameters](http://mitsuhiko.github.io/redis-rs/redis/#connection-parameters) section.
