### ISSUE TITLE
TTL command not implemented

### ISSUE THREAD

**Issue by DarrenTsung** [mitsuhiko/redis-rs#158]
From what I can see in https://docs.rs/redis/0.8.0/redis/trait.Commands.html, TTL is not implemented. See https://redis.io/commands/ttl. Just opening this as I didn't find any mention of it when searching the project.

I might get to opening a PR for this, but it's not very high priority ATM.

**Comment by lambdasqd** [comment]
See #160. Not sure I agree with the interface but it's consistent with all the other commands in the module (they all return a RedisValue).

Instead, would it be better to have an API that more strictly conforms to the definition of the TTL command?

For example, we could return an enum with the following:

```
enum RedisKeyState<V: RedisValue> {
    DoesNotExist, // version > 2.6, returned -2
    NoExpire,     // version > 2.6, returned -1
    Unknown,      // version < 2.6, returned -1
    Expire(V),    // returned non-negative integer
}
```

**Comment by badboy** [comment]
I don't see a point in supporting Redis < 2.6, it's an unsupported version upstream. I'm fine with not converting the return value at all.
