### ISSUE TITLE
Support async operation on sync connection

### ISSUE THREAD

**Issue by tangkhaiphuong** [mitsuhiko/redis-rs#161]
I use redis with r2d2 via crate r2d2-redis. The connection get from pool is normal connection so can't perform async query on command.

Does this crate support async query on sync connection or any way to workaround for this?
https://github.com/sorccu/r2d2-redis/issues/19#issuecomment-413734354

**Comment by badboy** [comment]
That's not possible (in the current model). The connection can either be sync or async, not both.
(Then again, the async support is new and experimental, so we are free to change it to what we need).

However, I think with more stuff moving to async, we might want to think about r2d2 being able to do async connection handling

**Comment by jwilm** [comment]
Someone started a project called bb8 which is an async r2d2. Maybe that’s the right path here? https://github.com/khuey/bb8

**Comment by badboy** [comment]
<3 that name
