### ISSUE TITLE
crates.io version bump for TTL

### ISSUE THREAD

**Issue by jkcclemens** [mitsuhiko/redis-rs#164]
Hi!

I was just wondering if a quick version could be pushed to crates.io so that TTL commands can be used with `r2d2` and `r2d2_redis` without needing `redis::cmd`.

Thank you for the awesome crate!

**Comment by badboy** [comment]
Will do as soon as I get to my laptop with developer credentials.

**Comment by badboy** [comment]
https://github.com/mitsuhiko/redis-rs/commit/d70e08d4022bc53e6660cac48b0cae5145241507
