### ISSUE TITLE
MULTI/EXEC

### ISSUE THREAD

**Issue by jkcclemens** [mitsuhiko/redis-rs#166]
Is there any way to handle `MULTI` and `EXEC` besides doing it manually? I couldn't find anything in the docs or in the issues.

If not, that would be an awesome thing to have!

**Comment by badboy** [comment]
You can use [an atomic pipeline](https://docs.rs/redis/0.9.0/redis/struct.Pipeline.html#method.atomic) or [a transaction](https://docs.rs/redis/0.9.0/redis/fn.transaction.html)
