### ISSUE TITLE
SSL support missing?

### ISSUE THREAD

**Issue by shadowmint** [mitsuhiko/redis-rs#168]
I see no open or closed issues regarding SSL support; is this just not supported?

From https://redislabs.com/lp/redis-enterprise-rust/:

> How to Use an SSL Connection with Redis Enterprise
>
> redis-rs or async-redis does not support SSL connections natively. For an added security measure, you can secure your connection using stunnel. 

...and indeed, I cannot connect to an SSL redis instance from azure with this library.

Is this a feature that is coming / considered, or should I be looking else-where?

Repro:

```
extern crate redis;

fn main() {
    let client = redis::Client::open("redis://XXX@YYYYYDFFDA.redis.cache.windows.net:6380").unwrap();
    let conn = client.get_connection().unwrap();
    let results:Vec<String> = redis::cmd("KEYS").arg("*").query(&conn).unwrap();
    results.iter().for_each(|i| {
        println!("{}", i);
    });
}
```

Returns:

> An existing connection was forcibly closed by the remote host. (os error 10054)

This appears to be the result for any redis server on an SSL connection.

**Comment by duergner** [comment]
@badboy would you accept a PR to add TLS support to `redis-rs`?

**Comment by nbari** [comment]
https://redis.io/topics/encryption
> SSL/TLS is supported by Redis starting with version 6 as an optional feature that needs to be enabled at compile time.

would be nice to have

**Comment by badboy** [comment]
> [redis.io/topics/encryption](https://redis.io/topics/encryption)
> 
> > SSL/TLS is supported by Redis starting with version 6 as an optional feature that needs to be enabled at compile time.
> 
> would be nice to have

https://github.com/mitsuhiko/redis-rs/pull/244
