### ISSUE TITLE
Feature request: make RedisServer (from tests/support) part of public API

### ISSUE THREAD

**Issue by davechallis** [mitsuhiko/redis-rs#169]
For testing my own applications that use the redis, I've found the code from https://github.com/mitsuhiko/redis-rs/blob/master/tests/support/mod.rs to be very useful.

It would be great if that was available to use from the redis crate, instead of having to copy/modify the source to do something similar in my own applications.

**Comment by badboy** [comment]
I don't want to maintain yet another API for public consumption, where we tailor it specifically to our needs in testing.
That module is small and self-contained, copying and adopting to your own needs is the way to go.

**Comment by davechallis** [comment]
No worries at all, sounds perfectly reasonable to me.
