### ISSUE TITLE
Mixing sync and async connections results in Connection refused (os error 111)

### ISSUE THREAD

**Issue by jeromegn** [mitsuhiko/redis-rs#175]
I've been playing with this crate a lot and it's been great. However, when I tried mixing both sync and async connections, I ran into troubles.

Example reproduction:

```rust
extern crate futures;
extern crate redis;
extern crate tokio;

use futures::Future;

fn main() {
    let client = redis::Client::open("redis://localhost:6379").unwrap();

    let conn = client.get_connection().unwrap();

    redis::cmd("SET")
        .arg("foo")
        .arg("bar")
        .query::<()>(&conn)
        .unwrap();

    let cclient = client.clone();

    tokio::run(futures::lazy(move || {
        cclient
            .get_shared_async_connection()
            .map_err(|e| println!("error getting shared conn: {}", e))
            .and_then(|conn| {
                redis::cmd("GET")
                    .arg("foo")
                    .query_async(conn)
                    .map_err(|e| println!("error querying async: {}", e))
                    .and_then(|(_, s): (_, String)| {
                        println!("got result: {}", s);
                        Ok(())
                    })
            })
    }));
}
```

This program will output:
> error getting shared conn: Connection refused (os error 111)

Is this not supported?

In my real use case, I'm invoking a lua script (there's no async invocation API, so I need a sync connection) and then setting extra hash keys asynchornously.

**Comment by badboy** [comment]
async support is a bit experimental at the moment. If using both is actually causing problems we should either fix that or make it impossible to mix both things.

I currently don't have the time to take a closer look though

**Comment by jeromegn** [comment]
Alright, I might just stick with the synchronous interface for now then. Thanks!
