### ISSUE TITLE
Query async on pipeline doesn't work correctly

### ISSUE THREAD

**Issue by ThorburnT** [mitsuhiko/redis-rs#177]
http://mitsuhiko.github.io/redis-rs/redis/struct.Pipeline.html#method.query_async method consumes self, a `Pipeline`. But all of the methods on `Pipeline` like `cmd` and `arg` return `&mut Pipeline`, effectively rendering `query_async` on `Pipeline` useless, unless I'm missing something obvious. 

A bit of a hacky solution with mem::replace will solve the problem, but I'm sure this isn't the intended way for this to work.

```rust

    redis::Pipeline::query_async(
    std::mem::replace(
        redis::pipe()
            .atomic()
            .cmd("HGET")
            .arg(hash_key1)
            .arg(id1)
            .cmd("HGET")
            .arg(hash_key2)
            .arg(id2),
        redis::pipe(),
    ),
    conn,
)
```

**Comment by Marwes** [comment]
The easiest way is just to add an intermediate variable or clone the `Pipeline`.

```
let mut pipe = redis::pipe();
pipe.atomic()
            .cmd("HGET")
            .arg(hash_key1)
            .arg(id1)
            .cmd("HGET")
            .arg(hash_key2)
            .arg(id2)
pipe.query_async();
```

Not as ergonomic however :/.

The long term solution is to refactor the API to take references but that can't be done until async/await hits stable.

**Comment by ThorburnT** [comment]
I don't know why I didn't think of the first. Thanks, this is a bit of a nicer way than mine. Personally, I can't wait for async/await
