### ISSUE TITLE
async is a reserved keyword

### ISSUE THREAD

**Issue by jgillich** [mitsuhiko/redis-rs#180]
Not sure if this is a recent change in Rust (maybe in the 2018 edtion?):
```
use redis::async::SharedConnection;

[rustc]
expected identifier, found reserved keyword `async`

expected identifier, found reserved keyword
```

**Comment by Marwes** [comment]
You can use `r#async` in place of  `async`. Meant to make a PR to fix this issue but I simply don't know a better name for atm.

**Comment by jwilm** [comment]
@Marwes re: naming bikeshed -- `aio` might capture the idea succinctly

**Comment by codesections** [comment]
The same is true for `try`—it's also a reserved keyword in the 2018 Edition, which means the simple examples in the README don't compile without converting to `r#try`.

Not a huge issue, but slightly offputting for a first impression.
