### ISSUE TITLE
Plans to add async pubsub?

### ISSUE THREAD

**Issue by mdenchev** [mitsuhiko/redis-rs#183]
It seems that pubsub is not implemented in the async version. Is it planned to be and would be it hard to add? I'll try to add it but wanted to know if it's being worked on or if there are specific difficulties to do so?

**Comment by emschwartz** [comment]
@mdenchev How's this going? I'm also interested in async version and might be able to help implement it if it's not especially complicated.

**Comment by mdenchev** [comment]
@emschwartz Sorry, haven't had time recently (and need to spend more time getting familiar with tokio). It's worth looking at https://github.com/benashford/redis-async-rs if it meets your needs for pubsub.

**Comment by codesections** [comment]
Has anyone started implementing an async pubsub?  I was talking with @tobz who also offered to help with a PR.

If no one else has started on this, I'll get started as soon as I can get my head around the `redis-rs` codebase.  (Lack of async pubsub support is a blocker on another project, so I'm very motivated to see this implemented.)

If someone _has_ started on it, how can I help?

**Comment by jwilm** [comment]
I implemented the most recent sync PubSub API, and I am not working on an async version. The only other person I can think of that might be working on it would be @Marwes who did most of the async work to date. Everyone else in this thread claims to not be working on it.

One of the neat properties of the synchronous PubSub API is that it statically prevents use of the underlying connection for commands illegal in subscribed mode. From the Redis docs,

> Once the client enters the subscribed state it is not supposed to issue any other commands, except for additional SUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE and PUNSUBSCRIBE commands.

It would be interesting to see this type safety reproduced in the async implementation of pubsub. It might save some time to get a consensus on what the API should look like before writing code. I think the floor is open at this point if anyone wants to make such a proposal.

**Comment by codesections** [comment]
That sounds great.  I'll follow up with an API proposal tomorrow.

**Comment by Marwes** [comment]
I am not working on it at least (have no need for it).

**Comment by codesections** [comment]
After looking into this a bit more, I've realized that we're 90% of the way done with implementing a low-level API for async pubsub based just on the good work @Marwes did implementing the low-level async API in general.  Consider this code, which already works:

```rust
use redis;
use tokio::prelude::*;

fn main() {
    let client = redis::Client::open("redis://127.0.0.1/").unwrap();
    let connect = client.get_async_connection();
    tokio::run(
        connect
            .and_then(|connection| {
                redis::cmd("PUBLISH")
                    .arg("chanel_name")
                    .arg("Hello, world")
                    .query_async(connection)
                    .map(|(_connection, result)| result)
            })
            .then(|result| {
                assert_eq!(result, Ok(()));
                Ok(())
            }),
    );
}
```

This code asynchronously connects to the `channel_name` channel and publishes the message `Hello, world` to the chanel.  (Indeed, if you are subscribed to the channel with a different client, you'll get the `Hello, world` message just fine.)  So the *publish* half of pubsub already works.  Similarly, this code compiles and runs today:

```rust
use redis;
use tokio::prelude::*;

fn main() {
    let client = redis::Client::open("redis://127.0.0.1/").unwrap();
    let connect = client.get_async_connection();
    tokio::run(
        connect
            .and_then(|connection| {
                redis::cmd("SUBSCRIBE")
                    .arg("channel_name")
                    .query_async(connection)
                    .map(|(_connection, result)| result)
            })
            .then(|result| {
                assert_eq!(result, Ok(()));
                Ok(())
            }),
    );
}
```

This code asynchronously subscribes to the `channel_name` channel.  It even limits future commands while in that state; if you tried to pass a non-pubsub command, after subscribing, you'd get the error `An error was signalled by the server: only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context`.

All the existing API *doesn't* allow is receiving messages published to a channel after you've subscribed to that channel—right now, there's no way to read incoming messages to the `connection` (which is a `redis::async::Connection`).

So, my proposed API fixes this.  I suggest we add an `as_pubsub_stream` method to the `async::Connection` struct with approximately the following form:

```rust
fn as_pubsub_stream<'a>(&'a mut self) -> futures::future<futures::Stream<'a>>
```

(I'm not *entirely* sure whether this should be `as_pubsub_stream` or `to_pubsub_stream`—I know that `as` is only appropriate if the transformation is free, but I haven't figured out the implementation enough to know whether it will be.  So this could be `to_pubsub_stream`)

This API would let users return a stream of the values for the channel they've subscribed to.  We could later build a higher-level API on top of this low level one, but this seems like a logical place to start.

I'd appreciate any thoughts y'all care to offer, either about the design of this low-level API or about the best ways to implement it.

**Comment by GopherJ** [comment]
hello @codesections, how about `PSUBSCRIBE`, is it already implemented?
Thanks in advance for your reply!

**Comment by boydjohnson** [comment]
Hi All. I wanted to move things forward by proposing a PubSub design and hopefully we can do some brainstorming. 

So the main parts would be:
 -  add a method to  `aio::Connection`:   `as_pubsub(self) -> PubSub`
 -  implement the methods subscribe, psubscribe, unsubscribe, punsubscribe on PubSub.

For example subscribe would look like
```rust
    pub fn subscribe<
        T: ToRedisArgs,
        F: Fn(Msg) -> U + 'static,
        U: IntoFuture<Item = (), Error = RedisError> + Send,
    >(
        self,
        callback: F,
    ) -> impl Future<Item = Self, Error = RedisError>
```
Subscribe returns a Future as it needs to return itself and it is hard to return a stream of the same object without cloning.

I have this about implemented on my (fork)[https://github.com/boydjohnson/redis-rs]

https://github.com/boydjohnson/redis-rs/blob/6236e80e9677503126e0e500566d233cc5ca7577/src/aio.rs#L112-L120
I am missing returning the PubSub object so right now there is no way to call subsequent commands.

Looking for thoughts on this particular design, and suggestions.
