### ISSUE TITLE
Futures 0.3 support

### ISSUE THREAD

**Issue by jimmycuadra** [mitsuhiko/redis-rs#184]
I couldn't find an existing tracking issue so opening this to ask about in-progress or planned support for futures 0.3/stdlib futures.

**Comment by Marwes** [comment]
This should be easy to, there is some manual future implementations but they are very shallow so any changes ought to be minor. Just waiting for a stable release of it.

**Comment by jimmycuadra** [comment]
Does that mean you would not accept a PR that provides support for the alpha versions of the futures-preview crate?

**Comment by Marwes** [comment]
(Late response, sorry).

There is a compatibility layer so the current, old futures can still be used so I don't think it is high priority.

However, by hiding it behind a feature flag and locking testing to a specific nightly version I suppose it wouldn't interfere with anything else so adding alternate impls might not be too painful (not 100% on that though and I don't have the urge to try it myself until it stabilizes).

**Comment by jimmycuadra** [comment]
It might be better to just wait since stabilization seems like it's coming pretty soon (within the next release or so.)

**Comment by mehcode** [comment]
A similar change that would be nice is to remove tokio in favor of https://github.com/rustasync/runtime - which enables the event loop and executor to be determined by the downstream crate.

**Comment by Marwes** [comment]
WIP @ https://github.com/Marwes/redis-rs/tree/std_future

**Comment by badboy** [comment]
landed in #232
