### ISSUE TITLE
Namespace support

### ISSUE THREAD

**Issue by jimmycuadra** [mitsuhiko/redis-rs#188]
Is there a way of creating a client/connection that works like the `Redis::Namespace` type in the Ruby client? If you're not familiar with it, it's a wrapper type that prefixes all key names with a string. It's useful for sharing a single Redis database with multiple applications so they won't accidentally overwrite each other's keys.

I don't see an obvious way of doing this with the way this crate is implemented, nor do I see an obvious way of proceeding to add this feature.

Is this something that would be desired in-crate? If so, any suggestions on how to approach it?

**Comment by badboy** [comment]
No, this crate doesn’t have this feature.
I think it’s a better idea to have a small wrapper function to pass your keys through to create them prefixed with what your application requires.

**Comment by jimmycuadra** [comment]
I don't think that will work for my particular use case. In my program, a value will be passed to a user-supplied callback which I'd like to expose a `Commands`-style interface to Redis, but that will automatically prefix all keys with a certain string. There isn't really a generic way to do this from what I can tell, partly because this library doesn't distinguish between key names and additional arguments, and partly because there isn't a place to "hook into" setting the key name. I could just write a custom implementation for every single function in `Commands` but that's a lot of work and would be hard to sync any upstream changes made to this crate.

**Comment by badboy** [comment]
As mentioned above I currently have no plans to support namespacing keys in this library.

Closing this bug.
