### ISSUE TITLE
sharing connection between multiple threads

### ISSUE THREAD

**Issue by anandanand84** [mitsuhiko/redis-rs#191]
Cound not share connection between multiple threads.

adding below code will throw compilation error.
lazy_static! {
    static ref meta_client :Client = redis::Client::open("redis://localhost:6379/").unwrap();
    static ref conn :Connection = meta_client.get_connection().unwrap();
}

`std::cell::RefCell<redis::connection::ActualConnection>` cannot be shared between threads safely

`std::cell::RefCell<redis::connection::ActualConnection>` cannot be shared between threads safely

help: within `redis::Connection`, the trait `std::marker::Sync` is not implemented for `std::cell::RefCell<redis::connection::ActualConnection>`
note: required because it appears within the type `redis::Connection`
note: required by `lazy_static::lazy::Lazy`rustc(E0277)

Is there a way to reuse the connection between multiple threads ?

**Comment by Marwes** [comment]
You could wrap the connection in a `Mutex` and it should let you use `lazy_static` at least. But then you can still only use it from one thread at a time so I am not sure if that is what you want? (For async uses https://docs.rs/redis/0.10.0/redis/async/struct.SharedConnection.html does support doing concurrent queries since it has internal synchronization.

**Comment by useraccessdenied** [comment]
> You could wrap the connection in a `Mutex` and it should let you use `lazy_static` at least. But then you can still only use it from one thread at a time so I am not sure if that is what you want? (For async uses https://docs.rs/redis/0.10.0/redis/async/struct.SharedConnection.html does support doing concurrent queries since it has internal synchronization.)

SharedConnection seems to be removed from recent versions of redis-rs. Any recommendations on what should be used instead?

**Comment by Marwes** [comment]
It was just renamed to ﻿https://docs.rs/redis/latest/redis/aio/struct.MultiplexedConnection.html

**Comment by useraccessdenied** [comment]
> It was just renamed to ﻿https://docs.rs/redis/latest/redis/aio/struct.MultiplexedConnection.html

Thank-you!
