### ISSUE TITLE
[Question] bool support?

### ISSUE THREAD

**Issue by Geobert** [mitsuhiko/redis-rs#205]
Hi!

Thank you for this crate!

Does `redis-rs` support `bool` type?

I'm storing a bool:
```rust
.hset(&prod_key, PROD_STATE, false)
```

and when reading back:
```rust
let is_done: bool = c.hget(&prod_key, PROD_STATE).unwrap();
```

It's failing with:

> panicked at 'called `Result::unwrap()` on an `Err` value: Response was of incompatible type: "Response type not bool compatible." (response was string-data('"false"'))', 

It seems that it's coming back as a string?

**Comment by badboy** [comment]
Yes. Redis itself doesn't know bools as a data type it can store. It only has binary blobs (and integers to some extent).

* [We do convert booleans to a string (true or false) when writing into Redis](https://github.com/mitsuhiko/redis-rs/blob/9d0993e6caf5262ca691309887b382149fe8c254/src/types.rs#L576-L583).
* [We do convert `"1"`/`"0"` and several other things to bool when reading from Redis](https://github.com/mitsuhiko/redis-rs/blob/9d0993e6caf5262ca691309887b382149fe8c254/src/types.rs#L864-L882).

So ... this is more or less incompatible (see #106).
I'm actually considering calling it a mistake (as mitsuhiko does) and remove the conversions and then let the user (that would be you) handle conversion.

My suggestion: handle the conversion now yourself.
Does that make sense?

**Comment by Geobert** [comment]
yes it does, thank you for your answer!

**Comment by dthul** [comment]
The same issue just bit me as well. Maybe this could be made less of a pitfall with the next semver breaking release?
