### ISSUE TITLE
[Question] what does `smembers` returns if key does not exists?

### ISSUE THREAD

**Issue by Geobert** [mitsuhiko/redis-rs#207]
Hi,

I'm having trouble to find what `smembers` returns when the key does not exist.
```
let v: Vec<u32> = c.smembers("key")?;
```
and 
```
let v: Option<Vec<u32>> = c.smembers("key")?;
```
are both failing with "Response was of incompatible type"

Cheers!

**Comment by badboy** [comment]
<details>
<summary>Details</summary>

kkk kk

</details>

**Comment by badboy** [comment]
Sorry for the closing/opening. That was me hitting the wrong button.

```rust
let v: redis::Value = con.smembers("key")?;
println!("v: {:?}", v);
```

=>

```
v: bulk()
```

That's what it actually returns. However both `Vec<u32>` and `Option<Vec<u32>>` do work for me without problems (giving me an empty vector or `None` respectively)

**Comment by Geobert** [comment]
Thanks for your answer, I've asked with my head sleepy and just before bed. I'm not sure anymore that the line I've pointed is the cause of my unit test failure anymore… I'll keep you posted here :D

**Comment by Geobert** [comment]
Yeah, I should have put more logs before asking, it was totally unrelated to this line. Thanks anyway, I've learned which type is returned :D
