### ISSUE TITLE
New minor release with recent build.rs removal (fixes cross-compilation)

### ISSUE THREAD

**Issue by awakecoding** [mitsuhiko/redis-rs#212]
I'm working on cross-compiling from Linux to Windows, and I encountered an issue where the unix socket feature is incorrectly detected and enabled. A recent commit (https://github.com/mitsuhiko/redis-rs/commit/9d0993e6caf5262ca691309887b382149fe8c254) removes the detection entirely, which makes it work for me. However, there is currently no release with this fix, so if a new minor release could be made, it would be appreciated :)

**Comment by badboy** [comment]
I'm gonna work on a release tomorrow when I get the time (it's gonna be a major release though ;))

**Comment by badboy** [comment]
Published 0.11.0-beta.1.
Will cut a final release in about a week unless anything comes up.

**Comment by awakecoding** [comment]
thanks! :)
