### ISSUE TITLE
Shouldn't there be a way to check if a value is nil?

### ISSUE THREAD

**Issue by sntdevco** [mitsuhiko/redis-rs#213]
So let's say I do something like:
```rust
// redis::nil is an enum that gives a nil
if con.get("key") == redis::nil {
    println!("The value doesn't exist!");
} else if con.get("key") != redis::nil {
    // Do something with the key
} else {
   println!("Server error!");
}
```
Is there any way to achieve this at the moment (maybe without breaking the library)?

**Comment by sntdevco** [comment]
cc @badboy

**Comment by sntdevco** [comment]
Found a solution. Closed as this has been resolved

**Comment by sntdevco** [comment]
Found a solution. Closed as this has been resolved

**Comment by gak** [comment]
For anyone who has come here and wanted what the solution was. Just use an `Option<T>` as your type, described in https://github.com/mitsuhiko/redis-rs/issues/246#issuecomment-545314810.

**Comment by ohsayan** [comment]
> For anyone who has come here and wanted what the solution was. Just use an `Option<T>` as your type, described in https://github.com/mitsuhiko/redis-rs/issues/246#issuecomment-545314810.

I'm sorry, I had forgotten about this completely. I'll share my solution in a while.

**Comment by ohsayan** [comment]
This what I had done:
```rust
// Assuming that `con` a `Connection` is already instantiated
let some_value = match con.get("superkey") {
    Ok(redis::Value::Data(bytes) => {
        let val: String = redis::from_redis_value(&bytes).unwrap();
        val
    },
    _ => panic!("Oh no, something's wrong"),
};
// `some_value` variable should now have a `String`
```
