### ISSUE TITLE
Make `Commands` trait more generic (to support futures)

### ISSUE THREAD

**Issue by application-developer-DA** [mitsuhiko/redis-rs#214]
`redis-rs` does support async API, however it seems to be more like an experimental API. The `Commands` trait is implemented for `ConnectionLike` connections, but async version has its own `ConnectionLike` trait and it seems that because of that the `Commands` trait is not implemented for it.

Perhaps it makes sense to make `ConnectionLike` more generic, so that it returns not a `RedisResult` but something like `Self::ResultType<Value, Error>`, so that we can use all these functions from `Commands` crate for both sync and async versions of `Connection`. Otherwise the async version is not that easy to use (compared to the  sync version).

Futures / Tokio is becoming more and more common on the server side, so I think it would be nice to make async API more "user-friendly" and easy-to-use.

**Comment by badboy** [comment]
Looks like it is not too hard to re-implement the commands as needed for the async `ConnectionLike` object: https://github.com/mitsuhiko/redis-rs/commit/aad345227857a5bb5e0f86d89f30cdd3ed249853

**Comment by application-developer-DA** [comment]
If I understood the implementation right, that would require basically copy-pasting the implementation for each command from `Command` trait so that it's implemented in `aio::Command`, wouldn't it?

I might be wrong, but it looks more or less like a copy-paste of https://github.com/mitsuhiko/redis-rs/blob/master/src/commands.rs#L147

**Comment by badboy** [comment]
It is now. I did so to show it quickly. It might be possible to integrate that into the existing macro, therefore making it unnecessary to copy-paste it

**Comment by badboy** [comment]
There we go: https://github.com/mitsuhiko/redis-rs/commit/4b907804fd3488fc7c8df0ef56a353c779754682
Implemented as an `AsyncCommands` trait, re-using the already existing call into the macro.

**Comment by application-developer-DA** [comment]
Ah, nice. Yeah, that's indeed a quick way to do it :+1: 

My only concern with this approach is that some functions will still be missing (`sscan()` and the rest of the things which are written separately). Also I think that redis features which are currently implemented inside a separate crate (https://github.com/mitsuhiko/redis-rs/issues/162) will have to adapt their API as well.
