### ISSUE TITLE
[Question] Would you accept a PR for RediSearch?

### ISSUE THREAD

**Issue by lamafab** [mitsuhiko/redis-rs#216]
Hi

Currently there does not seem to be a library for RediSearch (redis module). I'd like to work on it eventually, but before I begin I'd like to know if you would accept that implementation as a PR for this repository? Or would you prefer a separate repo/crate?

I'd appreciate your thoughts.

**Comment by badboy** [comment]
I think this fits much better into an external library, built on top of redis-rs.
Happy to answer questions on how that could work (though I'm not gonna have opinions on the API)
