### ISSUE TITLE
How to properly share a SharedConnection?

### ISSUE THREAD

**Issue by vflopes** [mitsuhiko/redis-rs#224]
I have the following code to manage named shared connections:

```rust
use std::collections::HashMap;
use futures::*;
use std::sync::*;

pub struct Bus {
    client: Arc<redis::Client>,
    connections: Arc<RwLock<HashMap<&'static str, redis::aio::SharedConnection>>>
}

impl Bus {
    pub fn new (client: redis::Client) -> Bus {
        Bus {
            client: Arc::new(client),
            connections: Arc::new(RwLock::new(HashMap::new()))
        }
    }
    pub fn get_connection(&self, name: &'static str) -> impl Future<Item=redis::aio::SharedConnection, Error=redis::RedisError> {
        
        let read_conns = Arc::clone(&self.connections);
        let write_conns = Arc::clone(&self.connections);
        let client = Arc::clone(&self.client);

        future::lazy(move || {

            let read_conns = read_conns.read().unwrap();

            if !read_conns.contains_key(name) {

                return future::Either::A(
                    client.get_shared_async_connection().and_then(move |connection| {
                        
                        let mut write_conns = write_conns.write().unwrap();
                        write_conns.insert(name, connection);
                        
                        future::ok(write_conns.get(name).unwrap().clone())

                    })
                );
                
            }

            future::Either::B(future::ok(read_conns.get(name).unwrap().clone()))
            
        })

    }
}
```

And using the Bus struct to execute some commands on Redis with Tokio's runtime:

```rust
use bus::*;
use futures::future;
use futures::future::Future;

fn main() {

    let client = redis::Client::open("redis://172.17.0.2/").unwrap();
    let bus = Bus::new(client);
    let connect = bus.get_connection("writer");

    tokio::run(connect.and_then(|con| {
        redis::cmd("SET")
            .arg("key1")
            .arg(b"foo")
            .query_async(con)
            .and_then(|(con, ())| {
                future::ok(())
            })
    }).then(|_| {
        Ok(())
    }));
    println!("This will never be printed :(");
}
```

And the command is executed, I can see on Redis that the **key1** was set, but the Tokio's runtime never goes idle, blocking the execution of the rest of the program. Am I missing something here? (I'm new to Rust)

Versions:
* rustc 1.36.0 (a53f9df32 2019-07-03)
* I tried to use the master branch of redis-rs and tha last stable version (0.11)
* futures = "0.1.28"
* tokio = "0.1"

**Comment by Marwes** [comment]
I responded to this in another issue but I guess this could be better documented https://github.com/mitsuhiko/redis-rs/issues/220#issuecomment-511723914

**Comment by vflopes** [comment]
I saw that answer and helped me to understand more about the SharedConnection :smiley: , but I thought there was a way to share the resources between the main thread and the Tokio's runtime.

Is there any reason that explains why the references to cloned SharedConnections are not freed at the end of the future's execution?

If I'm understanding correctly when the connection goes out of the scope and is not taken or borrowed by another scope it should be dropped. I even tried to force it calling `drop()` on **con** but nothing happened. Let me know if I am asking something out of the scope of this crate, I don't want to take your time!

BTW - This is a great crate guys, I work hard on Redis related software and I was the first one to provide Redis Streams implementations for NodeJS clients, hope one day I can help here just need to improve my Rust skills :baby:

**Comment by Marwes** [comment]
> Is there any reason that explains why the references to cloned SharedConnections are not freed at the end of the future's execution?

They are freed, however you also have `SharedConnection` references in your `Bus` struct which outlive the tokio runtime (/ the `tokio::run` call). It is those references that keeps the task that drives the queries alive.

Since the `SharedConnection` gets tied to the tokio runtime that spawned created I don't think it makes sense to share it outside of the `tokio::run` call but maybe I don't see the whole picture there.

**Comment by vflopes** [comment]
Thank you @Marwes , now it's making sense to me!

This case that I'm facing to share the **Bus** outside of the `tokio::run` is a corner case that I can solve by other ways (like spawning threads to do blocking stuff), so I don't think that it worth to put efforts here.

**Comment by Marwes** [comment]
If you do need to share it outside I would recommend adding a `close` method which simply removes (drops) the connections.

```


use bus::*;
use futures::future;
use futures::future::Future;

impl Bus {
    fn close(&self) {
        self.connections.write().unwrap().clear();
    }
}
fn main() {

    let client = redis::Client::open("redis://172.17.0.2/").unwrap();
    let bus = Bus::new(client);
    let connect = bus.get_connection("writer");

    tokio::run(connect.and_then(|con| {
        redis::cmd("SET")
            .arg("key1")
            .arg(b"foo")
            .query_async(con)
            .and_then(|(con, ())| {
                future::ok(())
            })
    }).then(|_| {
        connect.close();
        Ok(())
    }));
    println!("This will never be printed :(");
}```

**Comment by vflopes** [comment]
I tried this approach, but doesn't work because it would need to move the bus to the closure passed to `then` :\

In the code that you posted the close is called on `connect` and not on `bus`.

Just if someone need to deal with such case, the only way that this would work would be by passing the bus as an Arc reference:

```rust
use bus::*;
use futures::future;
use futures::future::Future;
use std::sync::*;

fn main() {

    let client = redis::Client::open("redis://172.17.0.2/").unwrap();
    let bus = Arc::new(Bus::new(client));
    let bus_ref = Arc::clone(&bus);
    let connect = bus.get_connection("writer");

    tokio::run(connect.and_then(|con| {
        redis::cmd("SET")
            .arg("key1")
            .arg(b"foo")
            .query_async(con)
            .and_then(|(con, ())| {
                future::ok(())
            })
    }).then(move |_| {
        bus_ref.stop();
        Ok(())
    }));
    println!("This will be printed :D");
}
```

And you can implement methods on Bus to remove only the used connections by Tokio's runtime, but that is something beyond this issue :smile:
