### ISSUE TITLE
PubSub disconnect handling

### ISSUE THREAD

**Issue by ShaneLillieRAD** [mitsuhiko/redis-rs#226]
I'm confused about how reconnecting a disconnected PubSub connection is supposed to be handled. Because of the mutable reference to the connection being held in the PubSub object, I'm finding it difficult to figure out how I'm supposed to create a new connection and a new PubSub object in a way that actually gets passed the borrow checker. Is there an example anywhere of how to go about doing this?

I'm able to determine that the connection has gone bad from the Error result from get_message() (because you can no longer query the connection's is_open(), again due to the mutable reference permanently held by the PubSub) but I'm not sure what I'm supposed to do from there. I've also verified that the underlying code isn't handling this for me (killing the network and bringing it back causes the PubSub to spam errors when it's polled).

**Comment by badboy** [comment]
Hm, I think that was indeed an oversight when we changed the code to require a mutable connection.

I guess (without testing or looking more at the code) it should be possible to drop the `PubSub` object (which holds the mutable reference).
I don't think returning the mutable reference in the error case would be the way to go.

**Comment by Luminoth** [comment]
Hm. Ok. I haven't as of yet been able to find a way to actually drop the pubsub and reattempt the connection without failing the borrow checker, but I'll keep working at it. It might be good to have an example somewhere if possible, since this seems fairly involved to get working right now.

**Comment by Marwes** [comment]
Wouldn't you `drop` the `PubSub` struct and then call `as_pubsub` again?

**Comment by Luminoth** [comment]
I don't believe that would work as-is in the case where the connection has died and needs to be reconnected, unless I've missed something. As far as I can tell there's no automatic reconnect happening in the library.

**Comment by Marwes** [comment]
If the entire connection is dead you would need redo the full connection again which isn't really compatible with the borrowed value in `PubSub` I guess. I don't think the fact that we changed it to be a mutable reference matters here though, the old `&` reference would have the same issue there (got a bit confused by that).

**Comment by Luminoth** [comment]
In terms of having to rebuild the connection entirely, the mutability definitely doesn't matter - it doesn't seem doable easily in either case as you said - but it does prevent the use of the is_open() method on the connection to see if it's still alive. That tho is entirely manageable through get_message() error checking.

**Comment by jwilm** [comment]
Hi, I might be able to shed a bit of light on this as I'm responsible for the latest PubSub API.

The singular goal with `as_pubsub` and the `PubSub` wrapper is to statically prevent misuse of the underlying connection while a subscription is active. Connection error handling was assumed to be outside of this.

Nominally, you want to handle connection errors by recreating the whole connection. This can easily be done with a connection pooler and using a two tiered run loop. The pooler isn't strictly necessary, but it does nicely memoize all of the connection info for creating new connections.

```rust
fn run(pool: &Pool) -> io::Result<()> {
    let mut conn = pool.get()?;
    let mut pubsub = conn.as_pubsub()?;
    pubsub.subscribe("foo")?;

    loop {
        // handle messages from pubsub; break out of function on io error
    }
}

fn main() {
    let pool = create_pool();
    loop {
        run(&pool);
    }
}
```

As long as there's not a connection issue, the code remains within the pubsub loop. If there is a connection error, all of the state is recreated on a new connection.

It may make sense to expose some utility methods on `PubSub` such as `is_open` if they would be helpful, however. In my experience, assuming an error from get_message is fatal and recreating the connection has been sufficient.

**Comment by ShaneLillieRAD** [comment]
Ah, interesting, ok. I'll give that a try and see how it goes. It seems tho like it should be a good fit for my use case tho. It would definitely be nice to have access to is_open() but like you said, it's definitely good enough to check the get_message() error.

Thanks for taking some time to go through that solution! I appreciate it.
