### ISSUE TITLE
when I use r2d2-redis, I got error

### ISSUE THREAD

**Issue by arlicle** [mitsuhiko/redis-rs#228]
```
    let manager = RedisConnectionManager::new("redis://127.0.0.1:6379").unwrap();
    let pool = r2d2::Pool::builder().build(manager).unwrap();
    let pool2 = pool.clone();
    let mut conn = pool.get().unwrap();
    let n: i64 = conn.incr("counter", 1).unwrap();
    let con = *conn;
    let x = conn.set("ccc", 10);
```

get error

```
error[E0283]: type annotations required: cannot resolve `_: redis::FromRedisValue`
  --> src/db/redis.rs:17:18
   |
17 |     let x = conn.set("ccc", 10);
   |     
```
or I use 

`redis::cmd("SET").arg("my_key").arg(42).execute(&mut *conn);
`
this code is ok 

but when I use 

`redis::cmd("GET").arg("my_key").query(&mut *conn);
`
get the same error

```
error[E0283]: type annotations required: cannot resolve `_: redis::FromRedisValue`
  --> src/db/redis.rs:18:37
   |
18 |     redis::cmd("GET").arg("my_key").query(&mut *conn);
```

How can I fix it ?

**Comment by badboy** [comment]
This is not a r2d2-specific problem.
redis-rs decodes whatever Redis returns into an appropriate Rust type, but for that it has to know which type you want.

For the `set` example above, this will do it:

```rust
let x: () = conn.set("ccc", 10).unwrap(); // or handle the Result
```

If you want to decode the value `get` returns yourself, this is the way to go:

```rust
let x: redis::Value = redis::cmd("GET").arg("my_key").query(&mut *conn).unwrap();
```

Or, if you want a String:

```rust
let x: String = redis::cmd("GET").arg("my_key").query(&mut *conn).unwrap();
```

Everything returns results, so the `unwraps` above should be replaced by proper error handling.

**Comment by arlicle** [comment]
thank you very much:)
