### ISSUE TITLE
Add support for EVAL and EVALSHA

### ISSUE THREAD

**Issue by bcashier** [mitsuhiko/redis-rs#230]
Hi

Is there a way to add support for EVAL and EVALSHA commands ?

EVAL: https://redis.io/commands/eval

EVALSHA: https://redis.io/commands/evalsha

Thank you

**Comment by badboy** [comment]
It's supported through [the `Script` struct](https://docs.rs/redis/0.11.0/redis/struct.Script.html).

**Comment by bcashier** [comment]
@badboy Thank you

But how to call that method from within a pool please ?

**Comment by badboy** [comment]
The example on that page shows how to use it. 
`invoke` takes the connection object, which you should get from your pool.

**Comment by bcashier** [comment]
@badboy Tried that.

But it is returning this error message:

```
let mut connection = rpool.get().unwrap();
the trait bound `r2d2::PooledConnection<r2d2_redis::RedisConnectionManager>: r2d2_redis::redis::ConnectionLike` is not satisfied

the trait `r2d2_redis::redis::ConnectionLike` is not implemented for `r2d2::PooledConnection<r2d2_redis::RedisConnectionManager>`

note: required for the cast to the object type `dyn r2d2_redis::redis::ConnectionLike`rustc(E0277)
```

Any solution for this if possible please ?

Thank you

**Comment by your-diary** [comment]
In my case, it worked like a charm.

Here's a complete example because the documentation contains only a snippet:

```rust
use redis::Script;

fn main() -> redis::RedisResult<()> {
    let client = redis::Client::open("redis://127.0.0.1/")?;
    let mut con = client.get_connection()?;

    let x = Script::new(
        r#"
            return ARGV[1]
        "#,
    )
    .arg(42)
    .invoke::<usize>(&mut con)?;

    println!("{}", x); //=> 42

    Ok(())
}
```
