### ISSUE TITLE
Broken pipe (os error 32)

### ISSUE THREAD

**Issue by sallyyu0** [mitsuhiko/redis-rs#237]
Could someone tell me what is the default timeout value for read? 

I'm getting an error when reading in client somehow.  Since it works from redis-cli, I'm wondering if this is caused by connection timeout. But I tried to set_read_timeout to none and still get the same error.

let val: Result<Vec<String>, RedisError> = conn.sinter(param.clone());
 
param = ["KEY1", "KEY2", "KEY3"]
=> failing "Broken pipe (os error 32)"
 
It works from redis-cli:
127.0.0.1:6379> sinter "KEY1" "KEY2" "KEY3"
1) "1"
127.0.0.1:6379>

**Comment by hydrocortisone** [comment]
@sallyyu0 So, what was the problem ? :D
