### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by gferon** [mitsuhiko/redis-rs#241]
Hi, I'd like to implement TLS support for `redis-rs` and I already have [an initial implementation that works for sync](https://github.com/gferon/redis-rs/tree/redis-tls) that's gated by a feature flag (`--tls`).

I just wanted to open an issue because I have a couple of questions:

* Would this be a welcome addition to `redis-rs`?
* I realized while adding a new variant of ActualConnection that matching on the enum variant everywhere is, to my understanding, very much similar to having dynamic dispatch of a trait implementation. Is there a reason it is done like this, and it shouldn't be done with `Box<dyn>`? I personally find that this makes using the feature flags much easier and this is the path I chose while hacking TLS in.
* How should the URL string look like? I had a quick look around, and there's nothing in the Redis Protocol spec, and it looks like other libraries that support TLS use `redis+tls` - I also thought of using the URI fragments to support insecure mode (no check on domain and certificate chain) which would make an URL look like `redis+tls://127.0.0.1:6380#insecure`.

Any feedback is appreciated.

**Comment by Marwes** [comment]
> I realized while adding a new variant of ActualConnection that matching on the enum variant everywhere is, to my understanding, very much similar to having dynamic dispatch of a trait implementation. Is there a reason it is done like this, and it shouldn't be done with Box<dyn>? I personally find that this makes using the feature flags much easier and this is the path I chose while hacking TLS in.

I looked at parameterize the connection types by any type that implements `Write + Read` and it seems that the only reason that is the way it is, is because connecting to an `url` forces the produced connection to be a known type which forces an enum for each backend. It should be solvable though.

**Comment by ajmwagar** [comment]
Hey everyone, 

Now that `async`/`.await` have standardized, and `redis-rs` has added support, are there any plans or updates for this?

If not, I could look into drafting a PR.

Please let me know.

Best,

Avery

**Comment by gferon** [comment]
Actually sounds like a great side-project, I'll get back at it today! I'm happy to collaborate with you @ajmwagar if you want.

**Comment by abhirockzz** [comment]
Hello! Wanted to check if this will be available in anytime soon? Thanks!
