### ISSUE TITLE
How to reliably check if response is nil?

### ISSUE THREAD

**Issue by MikaelCall** [mitsuhiko/redis-rs#246]
Is there a way to check if a Redis response is nil?

Currently I'm doing something like:
```rust
let db_result: String = connection.get(my_key);
if let Err(err) = db_result {
    if err.kind() == redis::ErrorKind::TypeError {
        println!("my_key was PROBABLY nil but I'm not certain...")
    }
}
```
which catches `nil` ... but also other type errors.

I guess I could use `Value` and then `from_redis_value` but that seems like a lot of unnecessary boilerplate. IMO it would be nice to have an error kind variant for `nil` so that we can simply do:
```rust
let db_result: String = connection.get(my_key)?;
```
and act on the error appropriately.

Looking at the code it seems like it would be sufficient to consider all match statements that uses the `ìnvalid_type_error` macro (also taking the 2 current `Value::Nil` arms into account).

Another option would be to have an `is_nil_response` method on `RedisError` but that seems like it is hard to implement without using the error description which i kind of a hack.

**Comment by Marwes** [comment]
Extracting `Option<String>` should do what you want. If you get `None` then a `nil` was returned.

https://github.com/mitsuhiko/redis-rs/blob/418512bf9171589b814da4c5ecb500e8747781e0/src/types.rs#L1074-L1081

**Comment by alidehghan** [comment]
what about async version?

**Comment by nihohit** [comment]
It works the same for async.
