### ISSUE TITLE
SharedConnection panicing with `executor has shut down`

### ISSUE THREAD

**Issue by elpiel** [mitsuhiko/redis-rs#248]
I have this test I am trying to make work that connects to Redis (creates a SharedConnection), the problem is that when I try to connect in `futures::future::block_on(async { ... })` for the test as it's async fn, I get a panic that `unwrap()` was called [here(aio.rs:447)](https://github.com/mitsuhiko/redis-rs/blob/master/src/aio.rs#L447) and the error is that `executor has shut down`.

I will try to create a minimum example to reproduce it, but thought that someone might now how to do it already.
I also tried other way like `#[tokio::test]`, but it doesn't work.
**Note 1:** I am using `nightly-2019-10-14`

**Comment by Marwes** [comment]
The currently released version depends on tokio 0.1. You will need to use https://github.com/mitsuhiko/redis-rs/pull/232 for tokio 0.2, or you must use https://docs.rs/redis/0.13.0/redis/struct.Client.html#method.get_shared_async_connection_with_executor and provide an `Executor` that spawns the task on a tokio 0.2 executor

**Comment by elpiel** [comment]
Yes, I just figured out that that this was the problem... I hope the 232 is soon merged in the alpha! Good work @Marwes !
