### ISSUE TITLE
Async connection API improvement?

### ISSUE THREAD

**Issue by importcjj** [mitsuhiko/redis-rs#250]
Hello, this library is great. And  I wrote an asynchronous connection pool, but the signature of the asynchronous function `query_async` presents a bit of a problem.

```rust 
pub fn query_async(&self, con: C) -> RedisFuture<(C, T)>
```

It prevents me from using `DerefMut` to quickly pass references, and now I can only do it in a cumbersome way. see 

[https://github.com/importcjj/mobc/blob/master/redis/examples/ping.rs#L18](https://github.com/importcjj/mobc/blob/master/redis/examples/ping.rs#L18)

Could you change it to use `&mut` just like the function `query`

```rust
pub fn query<T: FromRedisValue>(
    &self,
    con: &mut dyn ConnectionLike
) -> RedisResult<T>
```

Waiting for your reply.

**Comment by Marwes** [comment]
In the async/await branch that is how the api looks like https://github.com/mitsuhiko/redis-rs/pull/232

**Comment by importcjj** [comment]
Wow! Do you have a release plan?

**Comment by badboy** [comment]
#232 was merged and will be released soon.
