### ISSUE TITLE
Example with ".set()?" on home page doesn't compile

### ISSUE THREAD

**Issue by hfingler** [mitsuhiko/redis-rs#251]
I'm playing around with redis but when I try doing a set just like the example on the homepage, I get an error:

`let _ :() = con.set(bk, body)?;`

```
error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `std::ops::Try`)
   --> <my code>
    |
224 |         let _ : () = con.set("hi", "42")?;
    |                      ^^^^^^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
    |
    = help: the trait `std::ops::Try` is not implemented for `()`
    = note: required by `std::ops::Try::from_error`
```

Am I doing something wrong?
Also, it would be very helpful if there was a get example where the data is actually unpacked, because the compiler made me explicitly use a RedisResult.

**Comment by hfingler** [comment]
Welp, just figured it out. I have a dependency issue and I'm using redis 0.8, which is likely the issue.

**Comment by hfingler** [comment]
Sorry about spamming (lack of sleep and stuff) but the error persists even with 0.13. Tried the cmd example in the docs and it fails the same way:

```
error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `std::ops::Try`)
   --> <code> 
    |
226 |         let _ : () = redis::cmd("SET").arg("my_key").arg(42).query(con)?;
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
    |
    = help: the trait `std::ops::Try` is not implemented for `()`
    = note: required by `std::ops::Try::from_error`
```

**Comment by badboy** [comment]
This is not an error with redis-rs:

```
cannot use the `?` operator in a function that returns `()`
```

You need to ensure your function is returning a result, see [the book about it](https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-the--operator)
