### ISSUE TITLE
How can I do an async get and get a Vec<u8>? Getting   type annotations required

### ISSUE THREAD

**Issue by hfingler** [mitsuhiko/redis-rs#252]
I'm trying to do an async get, but I can't seem to satisfy the compiler to get the data out. All I can find says "If you don't care about the return value you may specify it as () to ignore it." (#170), but what if I do care? I want to get a Vec<u8> and I don't know how to specify it:

```
        conn.and_then(|con| {
            redis::cmd("GET").arg(bk)
            .query_async(con)
            .map(|t| t.1)
        }).then(|result| {
            result.expect("nope");
            Ok(())
        });
```

```
error[E0283]: type annotations required: cannot resolve `_: ::redis::FromRedisValue`
   --> <code>
    |
260 |             .query_async(con)
    |              ^^^^^^^^^^^

```

 How can I achieve this?

**Comment by badboy** [comment]
Assign it to a variable, so that you can give it a type:

```rust
let var: YourType = redis::cmd(...) ...
```

It might also work to give a type hint in the following closure:

```rust
...
}).then(|result: YourType| { ... 
```

Note: I recently merged a new async API, to support the new async/await syntax better.

**Comment by ollyde** [comment]
@hfingler also stuck here, async commands don't work properly. 

https://github.com/async-graphql/async-graphql/issues/1463
