### ISSUE TITLE
Lower number of dependencies?

### ISSUE THREAD

**Issue by dpc** [mitsuhiko/redis-rs#257]
Hi,

I am wondering if there's a room for lowering number of dependencies somehow - e.g. by making some of them optional. Right now I am not using any async APIs etc. but I still have to pull into my binary `tokio` and other deps recursively.

**Comment by badboy** [comment]
We could make the async part optional, with it being default enabled.
Happy to take a PR for that.

**Comment by mitsuhiko** [comment]
There is a lower number of dependencies now on master but further cutting it down would need some changes in combine.
