### ISSUE TITLE
Yank version with "*" deps

### ISSUE THREAD

**Issue by kornelski** [mitsuhiko/redis-rs#258]
An old version of `redis` has dependencies specified with `"*"` version requirement (`sha1 = "*"`, `rustc-serialize = "*"`, `unix_socket = "*"`, `url = "*"`).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because this old version of `redis` is unusable and may cause problems for Cargo, I suggest yanking it:

```bash
cargo yank --vers 0.0.1
```

**Comment by badboy** [comment]
I yanked everything < 0.5.2
