### ISSUE TITLE
Help with multiplexed connection

### ISSUE THREAD

**Issue by mattcollier** [mitsuhiko/redis-rs#262]
I'm looking at these two functions: https://github.com/mattcollier/redis-rs/blob/e24d1f34d0cb8dc8de96d5319717829361459353/src/client.rs#L63-L90

I'm working from the master branch of this module.  For some reason my `client` does not allow me to execute `get_multiplexed_tokio_connection`.  I'm not sure I want to run that or not anyway?

`get_multiplexed_async_connection` returns a tuple as described, but I do not know how to make use of it.  Attempting to use the returned `MultiplexedConnection`just results in a `broken pipe` error.

I see in the related tests that a `block_on_all` function is being used which I believe comes out of `tokio` but I do not know how it gets into scope in the test file or more importantly, if it's a requirement, how to implement it outside of the test file.

A minimal example or additional documentation or references to how to make use of this type of structure would be great.

**Comment by Marwes** [comment]
As long as you call the tokio function inside a tokio executor it should just work so I am not sure what causes the issue here. A minimal example would be helpful.

**Comment by mattcollier** [comment]
Here's my minimal example: https://gist.github.com/mattcollier/75241712bc4ca399226d4aab53c6cd1f

I suspect I'm not providing the proper tokio wrapper or some such, but should it be failing silently?

**Comment by Marwes** [comment]
The example works fine for me, might be an issue with the redis server you have maybe?

**Comment by mattcollier** [comment]
Wow!  Here's my versions, anything else we can compare?
```
redis-cli 5.0.3
rustc 1.40.0 (73528e339 2019-12-16)
```

**Comment by mattcollier** [comment]
Also, can you explain this?  https://gist.github.com/mattcollier/75241712bc4ca399226d4aab53c6cd1f#file-main-rs-L54

Versus what's shown in the test which apparently does not involve a tuple.

https://github.com/mitsuhiko/redis-rs/blob/master/tests/test_async.rs#L158

**Comment by Marwes** [comment]
Ok, sorry now I see it. I just ran the example as is and expected to see the error. Since you are calling the `*_async_*` instead of the `_tokio_` method you need to spawn the `driver` future, otherwise the socket will shut down when the `driver` future is dropped.

(The `_tokio_` method does exactly this inside it)

```rust
extern crate tokio;
extern crate redis;
extern crate futures;
use redis::{aio::MultiplexedConnection, RedisResult};
use futures::{future, prelude::*};

fn test_cmd(con: &MultiplexedConnection, i: i32) -> impl Future<Output = RedisResult<()>> + Send {
  println!("YYYY {}", i);
  let mut con = con.clone();
  async move {
    let key = format!("key{}", i);
    let key_2 = key.clone();
    let key2 = format!("key{}_2", i);
    let key2_2 = key2.clone();

    let foo_val = format!("foo{}", i);

    let () = redis::cmd("SET")
      .arg(&key[..])
      .arg(foo_val.as_bytes())
      .query_async(&mut con)
      .await?;
    let () = redis::cmd("SET")
      .arg(&[&key2, "bar"])
      .query_async(&mut con)
      .await?;
    redis::cmd("MGET")
      .arg(&[&key_2, &key2_2])
      .query_async(&mut con)
      .map(|result| {
          assert_eq!(Ok((foo_val, b"bar".to_vec())), result);
          Ok(())
      })
      .await
  }
}

fn my_test(i: i32) -> impl Future<Output = RedisResult<()>> {
  async move {
    println!("INSIDE MY_TEST {}", i);
    Ok(())
  }
}

async fn help_tokio() {
  let client = redis::Client::open("redis://127.0.0.1/").unwrap();

  client.get_multiplexed_async_connection()
    .and_then(|(con, driver)| {
        tokio::spawn(driver);

      // FIXME: this line is never reached is get_multiplexed_async_connection
      // failing silently?
      println!("HERE B");

      // FIXME: con is a tuple??
      let cmds = (0..100).map(move |i| test_cmd(&con, i));

      // let cmds = (0..100).map(move |i| my_test(i));
      future::try_join_all(cmds)
    })
    .map_err(|err| panic!("{}", err))
    .await.unwrap();
}

#[tokio::main]
async fn main() {
  println!("Main starting...");
  tokio::spawn(async move {
    println!("HERE A");
    help_tokio().await;
  }).await;
  // FIXME: this is never reached
  println!("Main done.");
}

```

**Comment by mattcollier** [comment]
If I attempt to use the `get_multiplexed_tokio_connection` method, I get the following, am I supposed to be able to access that function directly?
```
no method named `get_multiplexed_tokio_connection` found for type `redis::Client` in the current scope

help: there is a method with a similar name: `get_multiplexed_async_connection`
```

**Comment by mattcollier** [comment]
Submitted working example here: https://github.com/mitsuhiko/redis-rs/pull/263

**Comment by Marwes** [comment]
You need to enable to `tokio-rt-core` feature for it to be enabled.

**Comment by mattcollier** [comment]
I currently have "full" in the dependency now, I'll try being explicit maybe I need an additional crate?
```
tokio = { version = "0.2.6", features = ["full"] }
```

**Comment by Marwes** [comment]
You need to specify it on the redis crate `redis = { version = .., features = ["tokio-rt-core"] }
