### ISSUE TITLE
dump rdb

### ISSUE THREAD

**Issue by withlin** [mitsuhiko/redis-rs#291]
I want to send psync command. and dump rdb and aof. which connetion can I use to read rdb binary.

**Comment by badboy** [comment]
None really using redis-rs.
`PSYNC` is a special mode and does not follow the simple request-response model once the command has been sent.
You can however use a regular `TcpStream` to get the data and then decide on your own what to do with the following command stream.

**Comment by withlin** [comment]
en, but i want to use using redis-rs，and then get a TcpStream . Is this allowed?

**Comment by badboy** [comment]
It's a bit complicated and not one of the standard use cases of redis-rs.

It _could_ be build similarly to the PubSub functionality, but it's such a niche functionality that I won't build it (nor have the desire to accept code that builds it).
Looking at how `PubSub` does it, you might be able to do that using [`send_packed_command`](https://docs.rs/redis/0.15.1/redis/struct.Connection.html#method.send_packed_command) and [`recv_response`](https://docs.rs/redis/0.15.1/redis/struct.Connection.html#method.recv_response) on your own.

**Comment by withlin** [comment]
tks, i am fix it.
