### ISSUE TITLE
How to set generic type

### ISSUE THREAD

**Issue by viper6277** [mitsuhiko/redis-rs#292]
Hello, Rust newbie here... I was trying to figure out how to create a function to set a key with a generic value...

This works.... no problem
```rust
type UserId = u64;

fn redis_set_user(key_name:String, key_value:UserId, conn: &mut redis::Connection) -> redis::RedisResult<()> {
    let _ = conn.set(key_name, key_value)?;
    Ok(())
}
```

but when I try : 

```rust
fn redis_set_generic<T>(key_name:String, key_value:T, conn: &mut redis::Connection) -> redis::RedisResult<()> {
    let _ = conn.set(key_name, key_value)?;
    Ok(())
}
```

I get a 
```rust
the trait `redis::ToRedisArgs` is not implemented for `T`
```

I'll keep trying to figure it out and post a solution when I find one.

**Comment by Marwes** [comment]
```
fn redis_set_generic<T>(key_name:String, key_value:T, conn: &mut redis::Connection) -> redis::RedisResult<()>
    where T: redis::redisArgs // < ---- here
{
    let _ = conn.set(key_name, key_value)?;
    Ok(())
}
```

**Comment by viper6277** [comment]
> ```rust
> fn redis_set_generic<T>(key_name:String, key_value:T, conn: &mut redis::Connection) -> redis::RedisResult<()>
>     where T: redis::redisArgs // < ---- here
> {
>     let _ = conn.set(key_name, key_value)?;
>     Ok(())
> }
> ```
> 
> https://doc.rust-lang.org/stable/book/ch10-02-traits.html#trait-bound-syntax

@Marwes, thank you man, your solution worked, however I had to change it to... : 

```rust
where T: redis::ToRedisArgs
```
Probably because I'm on version "0.15.1".

I have a few more things I want to do to my test code....and then I'll come back and re-post my working code... thanks again... Eddie
