### ISSUE TITLE
Connect to IPv6 with interface fails

### ISSUE THREAD

**Issue by nils-van-zuijlen** [mitsuhiko/redis-rs#293]
I'm trying to connect to an IPv6 redis server the same way as with the `redis-cli` command below:

```
$ redis-cli -h fe80::cafe:beef%eno1
[fe80::cafe:beef%eno1]:6379> 
```

I'm trying to do it with the rust code
```rs
let client = redis::Client::open("redis://fe80::cafe:beef%eno1/").expect("Can't connect to redis");
```
But when I run it, I get the following error:
```
thread 'main' panicked at 'Can't connect to redis: Redis URL did not parse', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I also tried this alternative syntax, but I got the same result.
```rs
let client = redis::Client::open("redis://fe80::cafe:beef%eno1/").expect("Can't connect to redis");
```

**Comment by badboy** [comment]
In general IPv6 addresses in URLs need to be wrapped in `[` and `]` to be parsed correctly. Looks like the `%eno1` suffix however still won't work. I'd need to check how and if that's valid in URLs.

Can you try and build a [`ConnectionInfo`](https://docs.rs/redis/0.15.1/redis/struct.ConnectionInfo.html) directly?

**Comment by badboy** [comment]
With [this patch](https://github.com/mitsuhiko/redis-rs/commit/411601c64c0d1a93db8b8ac0a5d1d04d37ecd4b8) it could be possible to do it like this:

```rust
redis::Client::open(("fe80::cafe:beef%eno1", 6379))
```

**Comment by sallyyu0** [comment]
I used ConnectionInfo with ipv6 address wrapped in [] but failed with following error.
```
234:failed to get connection for cluster ConnectionInfo { addr: Tcp("[fd00:10:0:5:5861:50ff:fe00:85]", 6379), db: 0, passwd: None } : failed to lookup address information: Name or service not known
234:failed to get connection for cluster ConnectionInfo { addr: Tcp("[fd00:10:0:5:5861:50ff:fe00:a2]", 6379), db: 0, passwd: None } : failed to lookup address information: Name or service not known
234:failed to get connection for cluster ConnectionInfo { addr: Tcp("[fd00:10:0:4:5861:50ff:fe00:8e]", 6379), db: 0, passwd: None } : failed to lookup address information: Name or service not known
234:failed to get connection for cluster ConnectionInfo { addr: Tcp("[fd00:10:0:5:5861:50ff:fe00:94]", 6379), db: 0, passwd: None } : failed to lookup address information: Name or service not known
```

**Comment by badboy** [comment]
You shouldn't need the brackets (`[]`) in ConnectionInfo.

**Comment by sallyyu0** [comment]
yup, removed [] and it worked.

**Comment by sallyyu0** [comment]
Could you add an interface InfoConnectionInfo for ConnectionInfo since into_connection_info() is what has been used by all other applications but currently only string is available.

**Comment by sallyyu0** [comment]
There are places that connect() still uses string url stored in slots(ex: "redis://fd00:10:0:5:5861:50ff:fe00:85:6379") instead of ConnectionInfo. Can those be updated to use ConnectionInfo instead?

```
fn get_conn_info(redis_url: &str) -> Option<ConnectionInfo> {
    let v: Vec<&str> = redis_url.split("://").collect();
    if v.len() == 2 {
        let h: Vec<&str> = v[1].split(":").collect();
        let port: u16 = h[h.len() - 1].parse().unwrap();
        let (host, _) = v[1].split_at(v[1].len() - port.to_string().len() - 1);
        return Some(ConnectionInfo {
            addr: Box::new(ConnectionAddr::Tcp(host.to_string(), port)),
            db: 0,
            passwd: None,
        });
    } else {
        return None;
    }
}
```

**Comment by badboy** [comment]
Can you open a separate issue for that?
