### ISSUE TITLE
Async connection deadlocks with multiple runtime instances

### ISSUE THREAD

**Issue by nazar-pc** [mitsuhiko/redis-rs#295]
I'm suffering doing basic calls with asynchronous version of the client for more than an hour now.
The trick is that I'm creating a connection in one Actix runtime instance and then using it from a different instance in a different thread (potentially different runtime).
In that case simple calls simply get stuck, even though Redis definitely receives commands, but my thread is dead and execution doesn't go past `.await` point until app shutdown (at which point I can see either result or error, no idea why).

Having the same behavior with multiplexed async connection.

Here is a minimal test case:
```rust
#[cfg(test)]
mod tests {
    use redis::{AsyncCommands, Client, RedisError};
    use std::thread;
    use tokio::runtime::Runtime;

    #[test]
    fn test() {
        Runtime::new().unwrap().block_on(async {
            let client = Client::open("redis://127.0.0.1:6379/").unwrap();
            let mut connection = client.get_async_connection().await.unwrap();

            let jojn_handle = thread::spawn(move || {
                Runtime::new().unwrap().block_on(async {
                    let result: Result<u8, RedisError> = connection.zadd("x", "y", 1).await;
                    assert!(result.is_ok());
                });
            });
            jojn_handle.join().unwrap();
        });
    }
}
```

This test will never finish.

Any suggestions or fixes?

**Comment by Marwes** [comment]
You are blocking the outer runtime when you join the thread. Since it won't make progress on other tasks (such as the driver task for the redis connection). The inner runtime will end up being blocked.

**Comment by nazar-pc** [comment]
Why does it matter if I'm awaiting inside of the inner one for the command to be executed?

**Comment by nazar-pc** [comment]
Also in my app (which is bigger than above test) outer runtime (actix_rt) is not blocked, yet inner runtime (also actix_rt) is still in a separate thread, so if the behavior is the same, there must be a problem somewhere else.

**Comment by Marwes** [comment]
You aren't doing `await` though in the example `jojn_handle.join().unwrap();` blocks the entire thread which in turn blocks the outer runtime and eventloop which drives the redis connection.

**Comment by nazar-pc** [comment]
Hm... maybe my understanding is incorrect, but:
1) There is no event loop in Rust's Futures implementation, it is all polling-based
2) I already did `.await` to get connection, since it is not tied to particular runtime (and it doesn't seem to) it should not have any additional futures spawned on runtime directly, hence shouldn't really block anything

**Comment by Marwes** [comment]
The connection is tied to a runtime (https://github.com/tokio-rs/mio/). You can still use it from another runtime but only as long as the runtime that it is created still runs.

In this example it is unable to since the `join` call blocks the entire runtime.

**Comment by nazar-pc** [comment]
Well, this one doesn't block for 999 seconds. And it will only process result after... 999 seconds:
```rust
#[cfg(test)]
mod tests {
    use redis::{AsyncCommands, Client, RedisError};
    use std::thread;
    use tokio::runtime::Runtime;
    use tokio::time::Duration;

    #[test]
    fn test() {
        Runtime::new().unwrap().block_on(async {
            let client = Client::open("redis://127.0.0.1:6379/").unwrap();
            let mut connection = client.get_async_connection().await.unwrap();

            let jojn_handle = thread::spawn(move || {
                Runtime::new().unwrap().block_on(async {
                    let result: Result<u8, RedisError> = connection.zadd("x", "y", 1).await;
                    assert!(result.is_ok());
                });
            });

            tokio::time::delay_for(Duration::from_secs(999)).await;
            jojn_handle.join().unwrap();
        });
    }
}
```

**Comment by Marwes** [comment]
```rust
tokio::time::delay_for(Duration::from_secs(999)).await;
```

Yields the current task which allows the outer runtime to run. If you add a `prinln!` in the inner Runtime you can see that `zadd` runs as expected.

After that it does take 999 seconds due to the `delay_for` but then it shutsdown as expected (lower the time to ~5 seconds to see it easily).

You may need to run the test with `cargo test -- --nocapture` to see the print.

**Comment by nazar-pc** [comment]
You are right.
Still it definitely didn't work for me for some reason.
I'll close for now and will reopen when/if I have a reproducible example.
