### ISSUE TITLE
A runtime error occurs when the get_multiplexed_tokio_connection is called

### ISSUE THREAD

**Issue by runnerSnail** [mitsuhiko/redis-rs#301]
#### my question
> Hint that I have no tokio runtime，But the code is running on tokio and there is a run-time error

#### my code
```rust
use redis::{self, aio::MultiplexedConnection, RedisResult};
pub fn set(command: Command) -> CoreOp {
    println!("===>set");
    let fut1 = async move {
        // let connect = get_client(0).clone();
        let connect = redis::Client::open("redis://127.0.0.1:6379").unwrap();
        connect
            .get_multiplexed_tokio_connection()
            .and_then(|mut con| {
                async move {
                    redis::cmd("SET")
                        .arg("key1")
                        .arg(b"foo")
                        .query_async(&mut con)
                        .await?;
                    redis::cmd("SET")
                        .arg(&["key2", "bar"])
                        .query_async(&mut con)
                        .await?;
                    let result = redis::cmd("MGET")
                        .arg(&["key1", "key2"])
                        .query_async(&mut con)
                        .await;
                    assert_eq!(result, Ok(("foo".to_string(), b"bar".to_vec())));
                    Ok(util::async_result(&command.identity, "OK"))
                    // result
                }
            })
            .map_err(|err| panic!("{}", err))
            .await
    };
    CoreOp::Async(fut1.boxed())
}
```
#### Error stack information
> Finished release [optimized] target(s) in 0.13s
Copy "/Users/waniu/Desktop/study/deno_redis/target/release/libdeno_redis.dylib" to "/Users/waniu/Desktop/study/deno_redis/.deno_plugins/deno_redis.dylib"
running 1 tests
result--->1
redis://127.0.0.1:6379/0
data 0
result--->2
doc1
commondId 1
control {"command_type":"Cmd","client_id":0,"command_id":1}
===>set
thread '' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', src/libcore/option.rs:1185:5
stack backtrace:
0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
1: core::fmt::write
2: std::io::Write::write_fmt
3: std::panicking::default_hook::{{closure}}
4: std::panicking::default_hook
5: std::panicking::rust_panic_with_hook
6: std::panicking::continue_panic_fmt
7: rust_begin_unwind
8: core::panicking::panic_fmt
9: core::option::expect_failed
10: tokio::io::registration::Registration::new
11: tokio::net::tcp::stream::TcpStream::new
12: <std::future::GenFuture as core::future::future::Future>::poll
13: <std::future::GenFuture as core::future::future::Future>::poll
14: futures_util::future::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
15: <std::future::GenFuture as core::future::future::Future>::poll
16: <futures_util::future::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll
17: <futures_util::future::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll
18: <&mut S as futures_core::stream::Stream>::poll_next
19: futures_util::stream::stream::StreamExt::poll_next_unpin
20: <deno_core::isolate::Isolate as core::future::future::Future>::poll
21: <deno_core::es_isolate::EsIsolate as core::future::future::Future>::poll
22: <std::future::GenFuture as core::future::future::Future>::poll
23: tokio::runtime::basic_scheduler::BasicScheduler

::block_on
24: tokio::runtime::context::enter
25: deno::tokio_util::run_basic
26: deno::main
27: std::rt::lang_start::{{closure}}
28: std::panicking::try::do_call
29: __rust_maybe_catch_panic
30: std::rt::lang_start_internal
31: main
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.

#### Thank you for your answers. I would appreciate it！

**Comment by Marwes** [comment]
I think you may have forgotten to call `enable_io` on your runtime https://docs.rs/tokio/0.2.13/tokio/runtime/struct.Builder.html#method.enable_io . Otherwise there is no reactor running.

**Comment by runnerSnail** [comment]
##  my tokio executive code call enable_io

Dear brother 🤔

rust
```rust
pub fn create_basic_runtime() -> tokio::runtime::Runtime {
  tokio::runtime::Builder::new()
    .basic_scheduler()
    .enable_io()
    .enable_time()
    .build()
    .unwrap()
}

```
## toml
parent project
tokio = { version = "0.2", features = ["**rt-core**", "tcp", "udp", "process", "fs", "blocking", "sync", "io-std", "macros", "time"] }

child  project
redis = { version = "0.15.1", features=["**tokio-rt-core**"] }

**Comment by runnerSnail** [comment]
I got the solution from this problem [issue](https://github.com/mitsuhiko/redis-rs/issues/224)

**Comment by runnerSnail** [comment]
#### condition
Sorry to disturb you，But I can't find a solution. Maybe I'm too weak。I look forward to your guidance

#### question

I hope to write a dynamic plug-in for  [project1](https://github.com/denoland/deno/blob/a98512af9a123b77332f0e7a75cfce753b7189bc/cli/ops/plugins.rs#L23)

The plug-in will be executed by [project1](https://github.com/denoland/deno/blob/bdcb926b37d9ac79b58c66b418a9c37fa746eeb7/cli/lib.rs#L575)

```Rust
// The execution environment 
pub fn create_basic_runtime() -> tokio::runtime::Runtime {
  tokio::runtime::Builder::new()
    .basic_scheduler()
    .enable_io()
    .enable_time()
    .build()
    .unwrap()
}


pub fn run_basic<F, R>(future: F) -> R
where
  F: std::future::Future<Output = R> + 'static,
{
  let mut rt = create_basic_runtime();
  rt.block_on(future)
}

```

But when I call **get_multiplexed_tokio_connection**. A runtime error occurs
[my project](https://github.com/runnerSnail/deno_redis/blob/a1621298c0dcae8e647ca62805e8b3007492abcc/src/command/connect.rs#L18)
```rust

pub fn get_connection(command: Command) -> CoreOp {
    let fut = async move{
        let args: ConnectArgs = serde_json::from_slice(command.data.unwrap().as_ref()).unwrap();
        let url = format!(
            "redis://{}:{}/{}",
            args.host.unwrap(),
            args.port.unwrap(),
            args.db.unwrap()
        );
        println!("{}", url);
        let client = redis::Client::open(url).unwrap();
        let client_id: usize = CLIENT_ID.fetch_add(1, Ordering::SeqCst);
        CLIENTS.lock().unwrap().insert(client_id, client.clone());
        let mut write_conns = Arc::clone(&CLIENTS_CONNECT);
        let  connect: Arc<MultiplexedConnection> = Arc::new(client.get_multiplexed_tokio_connection().await.unwrap());
        let mut write_conns = write_conns.write().unwrap();
        write_conns.insert(client_id, connect.clone());
        Ok(Buf::from(client_id.to_string().as_bytes()))
    };
    CoreOp::Async(fut.boxed())
}

```

#### error

thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', src/libcore/option.rs:1185:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: tokio::io::registration::Registration::new
  11: tokio::net::tcp::stream::TcpStream::new
  12: <std::future::GenFuture<T> as core::future::future::Future>::poll
  13: <std::future::GenFuture<T> as core::future::future::Future>::poll
  14: <futures_util::future::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll
  15: <futures_util::future::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll
  16: <&mut S as futures_core::stream::Stream>::poll_next
  17: futures_util::stream::stream::StreamExt::poll_next_unpin
  18: <deno_core::isolate::Isolate as core::future::future::Future>::poll
  19: <deno_core::es_isolate::EsIsolate as core::future::future::Future>::poll
  20: <std::future::GenFuture<T> as core::future::future::Future>::poll
  21: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  22: tokio::runtime::context::enter
  23: deno::tokio_util::run_basic
  24: deno::main
  25: std::rt::lang_start::{{closure}}
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
  28: std::rt::lang_start_internal
  29: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
