### ISSUE TITLE
ZPOPMIN and ZPOPMAX commands

### ISSUE THREAD

**Issue by ajmwagar** [mitsuhiko/redis-rs#309]
Hey everyone, 

I've noticed that while `redis-rs` supports a wide variety of commands currently, including many for Sorted Sets, it is missing the ZPOPMIN and ZPOPMAX commands.  

Considering that the library already has support for Sorted Sets, it seems like ZPOPMIN and ZPOPMAX would be a worthwhile addition.

Are you open to adding these features? I can help implement them if you'd be willing to incorporate them into the library.

**Comment by badboy** [comment]
Sure, seems like a rather recent addition, but adding them should be simple. We'll happily take a PR.

**Comment by mcarson-sandia** [comment]
@badboy I have added support for zpopmin/zpopmax in #351. It passes all clippy lints but let me know if I need to make any changes to it.
