### ISSUE TITLE
aio::Connection is now !Sync ?

### ISSUE THREAD

**Issue by Luminoth** [mitsuhiko/redis-rs#317]
I didn't see anything in the CHANGELOG specifically calling out this breaking change, so I'm wondering if it was intentional that aio::Connection is now !Sync instead of Sync in 0.16.0?

**Comment by badboy** [comment]
Noone noticed, so noone bothered to document it.
In 0.16.0 we [switched to combine 4](https://github.com/mitsuhiko/redis-rs/pull/272).
`aio::Connection` now contains a `combine::stream::Decoder<AnySendPartialState, PointerOffset<[u8]>>`, and `AnySendPartialState` is a wrapper around `Box<dyn std::any::Any + Send>`, causing the whole thing to be `!Sync`.

Not sure if we can go back to `Sync`.
What are use cases where this is required?

**Comment by Luminoth** [comment]
The use case before was built around a single long-lived connection that was used across threads (wrapped in a RwLock). I've since switched over to just grabbing a new connection when I need one, since this app won't ever really be making a lot of them and I haven't gotten around to using a pool as of yet, and that actually seems to work just fine.

I guess on another documentation note while I'm here - has anyone setup an example of using the async PubSub? My previous sync usage was to create a thread for it with a message handling loop (using a timeout) inside of a connection handling loop (this was suggested to me in https://github.com/mitsuhiko/redis-rs/issues/226). It seems like the new async one should be fairly similar inside of a spawned async block, but I'm curious how the on_message() is intended to be used and if it can work together with something like tokio's timeout feature.

**Comment by barkanido** [comment]
Hey just found this. Is the `aio` connection `!Sync` again? (I am using version `0.20.0`) I might be wrong but I have created a connection using:
```rust
client.get_tokio_connection().await?
```
and then used it:
```rust
pub async fn get_custom_domains(redis_conn: &aio::Connection) -> Result<HashSet<String>> {
    let redis_resp = redis_conn.smembers("custom-domains").await;
    match redis_resp {
        Ok(data) => Ok(data),
        Err(e) => Err(anyhow!("failed to get custom domains fomr redis: {}", e)),
    }
}
```
but down the path I am getting:
```rust
// long error msg here...
   = help: the trait `Sync` is not implemented for `dyn Future<Output = Result<HashSet<std::string::String>, RedisError>> + Send`
note: future is not `Sync` as it awaits another future which is not `Sync`
  --> src/redis.rs:35:22
   |
35 |     let redis_resp = redis_conn.smembers("custom-domains").await;
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ await occurs here on type `Pin<Box<dyn Future<Output = Result<HashSet<std::string::String>, RedisError>> + Send>>`, which is not `Sync`
```

**Comment by extrawurst** [comment]
@barkanido no matter if T is `Sync` a `&T` is not

**Comment by barkanido** [comment]
Oh right I see. So what is the recommended way to use an async connection inside an async fn?

**Comment by Marwes** [comment]
The problem is that you only have a `&aio::Connection`, it needs to be `&mut aio::Connection`.

Is there no other error complaining about that instead? Smells like a compiler diaognostic bug if there aren't
