### ISSUE TITLE
Breaking changes for Debug/Display (previously Show/String) and Error traits

### ISSUE THREAD

**Issue by aldanor** [mitsuhiko/redis-rs#32]
https://github.com/rust-lang/rfcs/blob/master/text/0565-show-string-guidelines.md

It looks like there are just two things to be fixed in this library:
- `fmt::Show` has been renamed to `fmt::Debug` so the types should be `#[derive]`d from that
- `error::Error` no longer has a `description` method (however, you're supposed to implement `fmt::Display` on the derived type)

**Comment by badboy** [comment]
Today I went through the code and made all changes to make it compile again, it currently is at https://github.com/badboy/redis-rs/commits/alpha-fixes.
It uses a few small fixes to dependencies, that are not yet merged upstream. Once this happened, I will submit this as a PR for @mitsuhiko to merge and get redis-rs working again :)
