### ISSUE TITLE
RemoteError instead of IoError on killed connection

### ISSUE THREAD

**Issue by chridou** [mitsuhiko/redis-rs#320]
When a connection is killed via the command "CLIENT ID KILL" the killed connection does not fail with an IO Error but with a Remote Error indicating that the parser failed:

```
parse error: Parse error at 0
Unexpected `end of input`
```

The error still occurs if further commands are sent over the connection.

Sample code reproducing the issue can be found here: https://gist.github.com/chridou/d59f041540d786a22f184d0f655268ec

If an IO Error is indeed the expected error , it is possible that the`connection-manager` feature is  affected by this in possibly preventing it from reconnecting.

**Comment by badboy** [comment]
Seems bad indeed, we should bubble up EOF errors.
@Marwes could you take a look?
