### ISSUE TITLE
bool mismatched in ToRedisArgs and FromRedisValue

### ISSUE THREAD

**Issue by korvyr** [mitsuhiko/redis-rs#324]
[ToRedisArgs](https://docs.rs/redis/0.16.0/src/redis/types.rs.html#691-698) is converting boolean arguments into `b"true"` and `b"false"`.

That's all well and good, except [FromRedisValue](https://docs.rs/redis/0.16.0/src/redis/types.rs.html#977-995) is checking for an integer of 1 or 0.

This means any bool value of true stored using the [ToRedisArgs](https://docs.rs/redis/0.16.0/src/redis/types.rs.html#691-698) trait will ultimately return `Response was of incompatible type: "Response type not bool compatible." (response was string-data('"true"'))` when attempting to retrieve the same bool value using [FromRedisValue](https://docs.rs/redis/0.16.0/src/redis/types.rs.html#977-995).

**Comment by badboy** [comment]
Relevant: #106

**Comment by korvyr** [comment]
I suppose I'll draft a pull request that includes an addition in FromRedisValue that also accepts strings "true" and "false" as booleans.

Seems the most sensible way to fix it and maintain the integrity of dependent projects.

**Comment by badboy** [comment]
I think I'd actually agree [with mitsuhiko](https://github.com/mitsuhiko/redis-rs/pull/106#issuecomment-484003002)

> I would not remove the bool support for `FromRedisValue`, just `ToRedisArgs`

But I haven't spent much of a look since then

**Comment by korvyr** [comment]
Well it would certainly be your call in the end. I'm never a fan of removing capabilities from a project, but then that's why forking exists.

You may want to drop support from both ends if you're dead set on it, however. Having the project happily convert from boolean but not provide its own method for converting to boolean would likely only inspire more confusion.

Unless your conversion from covers a very broad spectrum of possibilities; 0/1, t/f, true/false, -1/0, etc.; there's likely to be an unhappy project somewhere.

Which is why you would always want to dictate the format for what goes in, so you know what comes out.

**Comment by badboy** [comment]
> Unless your conversion from covers a very broad spectrum of possibilities; 0/1, t/f, true/false, -1/0, etc.; there's likely to be an unhappy project somewhere.

Which would be even more reason not to handle coversion at all. Redis doesn't have a bool type and, as we can see, dictating how we encode a bool leads to problems.

**Comment by korvyr** [comment]
Isn't that the point of ToRedisArgs and FromRedisValue then? To convert what Redis does have into what Rust expects on the other end?

In the end it's not a big deal. Anyone can fix it by either relying on 0/1 integers or by forking and making it whatever they please.

But to me it seems removing the capacity for redis-rs to handle boolean values that a Rust programmer may pass it is two steps backwards from whatever step forward you may gain from removing it entirely.

**Comment by Terkwood** [comment]
PR #106 is still relevant to this effort, but is a bit out of date, shows a merge conflict, and originates from a deleted fork.

**Comment by Marwes** [comment]
We could just make `ToRedisValue` serialize a bool as `1/0`. That seems to be what redis uses anyway.

**Comment by Terkwood** [comment]
Yeah, if we want to support ToRedisArgs for bool, I'd vote for making the output conform to Redis's style instead of rust's

**Comment by weihanglo** [comment]
FYI, just skimmed [all Redis commands](https://github.com/redis/redis-doc/blob/c7757ea8df67e4c632d842d95e08392ceacaafa8/commands.json) and it appears that there is no boolean argument encoded in `0/1` style. In contrast, some string arguments, such as [`CLIENT CACHE YES|NO`](http://redis.io/commands/client-caching) and [`CLIENT KILL [SKIPME yes/no]`](http://redis.io/commands/client-kill) require `yes/no` which acts like a boolean type.
