### ISSUE TITLE
Could not find cluster module

### ISSUE THREAD

**Issue by cemremengu** [mitsuhiko/redis-rs#339]
I am new to rust so I am thinking this may be due to my inability, however I can use the cluster module for some reason. 
I am following [this example](https://docs.rs/redis/0.16.0/redis/cluster/index.html#example). Any ideas?

```
use redis::cluster::ClusterClient;

fn fetch_an_integer() -> String {
    // connect to redis
    let nodes = vec!["redis://127.0.0.1:7000/"];
    let client = ClusterClient::open(nodes).unwrap();
    let mut connection = client.get_connection().unwrap();
    let _: () = connection.set("test", "test_data").unwrap();
    let rv: String = connection.get("test").unwrap();
    return rv;
}

fn main() {
    println!("Hello, world!");
    println!("{}", fetch_an_integer())
}
```

```
error[E0432]: unresolved import `redis::cluster`
 --> src\main.rs:1:12
  |
1 | use redis::cluster::ClusterClient;
  |            ^^^^^^^ could not find `cluster` in `redis`
```

**Comment by Terkwood** [comment]
Hello!

You can solve this by specifying the cluster as a `features` entry in your Cargo.toml:

```toml
redis = { version = "0.16.0", features = [ "cluster"] }
```

You will also need to add an import to your program:

```rust
use redis::Commands;
```

I don't have access to a configured Redis cluster right now, so I wasn't able to test this end-to-end.  But I think it will work if you have cluster enabled on your own machine.

I made an example repo if you want to look.  It compiles happily :smile: 

https://github.com/Terkwood/redis-cluster-help

**Comment by cemremengu** [comment]
Thank you, I really appreciate it! Apologies for my lack of Rust knowledge with this 😄

**Comment by Terkwood** [comment]
Having these questions searchable in the issue tracker actually helps us move the project forward, and we got a Readme update as a side effect too! So thank YOU 🎂 😁

**Comment by Terkwood** [comment]
You need to enable the cluster feature. It is not turned on by default. See
https://doc.rust-lang.org/cargo/reference/features.html
