### ISSUE TITLE
Use Redis 6 in CI environment

### ISSUE THREAD

**Issue by Terkwood** [mitsuhiko/redis-rs#347]
# Problem Description

We found in #345 that the Travis CI environment is running Redis 5.  ACL commands, STRALGO, etc depend on Redis 6 to be installed.

This means that any tests which invoke Redis 6 features in the CI environment will fail.

We may be able to upgrade to Redis 6 by installing the debian `redis-server` using a backports repository.  (I've done this on a local debian workstation; not sure how difficult it will be in Travis).

## Sketch for a solution

[Travis CI has some documentation on installing specific packages to the CI environment](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-standard-infrastructure).

We would also need to make sure that the correct [backports repository](https://wiki.debian.org/Backports#Using_the_command_line) is available in the `apt` sources list.

Something like this?  I don't know if we're using debian `buster` in the CI environment, so please DOUBLE CHECK this suggestion before running it!

```yaml
# in .travis.yml
before_install:
  - sudo echo "deb http://deb.debian.org/debian buster-backports main contrib non-free" >> /etc/apt/sources.list
  - sudo apt-get -t buster-backports install redis-server
```

## Troubleshooting history

[Take a look at this failed build](https://travis-ci.org/github/mitsuhiko/redis-rs/jobs/701296341) from #345, and you can see that the Redis server is rejecting commands specific to Redis 6.

![travis_redis6_fail](https://user-images.githubusercontent.com/38859656/85436162-96339800-b556-11ea-8d50-b360958006db.png)

**Comment by Terkwood** [comment]
As an alternative example, `deno-redis` is configured to use Github Actions and pulls down Redis 6 via docker.   That client successfully tests against ACL commands.

https://github.com/denolib/deno-redis/runs/800375598?check_suite_focus=true

**Comment by Terkwood** [comment]
#345 includes an attempt to build Redis 6 from source

**Comment by weihanglo** [comment]
> As an alternative example, `deno-redis` is configured to use Github Actions and pulls down Redis 6 via docker. That client successfully tests against ACL commands.
> 
> https://github.com/denolib/deno-redis/runs/800375598?check_suite_focus=true

If we want to apply this approach, the `TestContext` may need to decouple from spawning redis-server by itself to some extent. See [Makefile of redis-db](https://github.com/redis/redis-rb/blob/cc4d1e023c71e7923de609947e2f5eefae20f2f9/makefile).

**Comment by weihanglo** [comment]
> #345 includes an attempt to build Redis 6 from source
> 
> [adaa6b5](https://github.com/mitsuhiko/redis-rs/commit/adaa6b517ac644779bcda11039b2ea3ab0f2e64b)

Both [redis-py](https://github.com/andymccurdy/redis-py/blob/05548a373f780c512bc7f7a12a18173d19437b12/.travis.yml) and aforementioned [redis-rb](https://github.com/redis/redis-rb/blob/cc4d1e023c71e7923de609947e2f5eefae20f2f9/makefile) build Redis from source. Though this solution is not elegant but still feasible (thanks to redis being a compile-time-friendly project 😅)

**Comment by Terkwood** [comment]
Yeah, if you can get it to work within the existing CI framework, I think that's a good step forward! Moving to github actions seems pretty daunting, honestly. 

But I do think installing from the Debian backports repo might _maybe_ cause a faster end to end testing flow. (So we may want to consider that in the future, or if the build process somehow runs into a problem)

**Comment by Terkwood** [comment]
I'm more than willing to make a totally separate branch to attempt installing Redis 6 Debian package via backports, I just may not get to it today

**Comment by weihanglo** [comment]
a066251 use an unofficial ppa and it works. Not sure if this is adequate solution.

**Comment by Terkwood** [comment]
No complaint here. If someone gets motivated to try the install from Debian backports, we can reference this issue.

**Comment by weihanglo** [comment]
I've tried adding debian buster backports but failed to install redis-server

The build is [here](https://travis-ci.org/github/weihanglo/redis-rs/jobs/701865118#L219). The error is

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 redis-server : PreDepends: init-system-helpers (>= 1.54~) but 1.29ubuntu4 is to be installed
                Depends: redis-tools (= 5:6.0.5-1~bpo10+1) but 5:5.0.4-1chl1~xenial1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Terkwood** [comment]
Thanks for trying. That package conflict might be possible to resolve but it looks like a minor headache to do so 😁 

Wow, https://github.com/antirez/redis/issues/1732 goes all the way back to 2014... 😅
