### ISSUE TITLE
Build broken because of "combine" dependency

### ISSUE THREAD

**Issue by zupzup** [mitsuhiko/redis-rs#358]
Hey,

Thanks for this fantastic library!

I just ran into an issue building my project depending on redis-rs 0.16.0 on CI. It worked a couple of hours ago, so I thought it might be dependency related, deleted my local `Cargo.lock` and retried, getting the same error.

This is the error:

![Screenshot from 2020-07-10 17-39-15](https://user-images.githubusercontent.com/942652/87172296-4da90800-c2d4-11ea-977a-2ffc6edd4288.png)

I traced it back to `combine` being upgraded (https://github.com/Marwes/combine) to 4.3.0 and the dependency not being pinned.

I'm not sure if there is a different way for me to depend on `redis-rs` without this happening, I "fixed" it now by adding

```
combine = "=4.2.1"
```

to my `Cargo.toml`.

Maybe it would be a good idea to pin these dependencies to an exact version?

I'm not sure what the ideal solution here is, I just thought it would be good to report it.

**Comment by SHDavies** [comment]
Just encountered this as well. Guess I'll use your "fix" for now.

**Comment by autodidaddict** [comment]
Just ran into this myself. Wasn't Rust supposed to save us from dependency hell? :trollface:

**Comment by msinojia** [comment]
I just ran into this issue as well. Your fix works for now until this is resolved. Thanks!

**Comment by Marwes** [comment]
Version 4.3.0 of combine is yanked for now. Doiing a cargo update should bring the lock file down to a version of combine that works.

The 4.3.0 version had a slight change to how the macro arguments were accepted,

```rust
match $read {
    ref mut read => ...
}
// changed to 

match $read {
     mut read => ...
}
```

This worked around a lifetime problem that the first version had in an added feature but it seems it ended up breaking the way redis passed the read argument (but not in my tests in combine).

Sorry for the inconvenience!
