### ISSUE TITLE
0.17 (or 0.16.1) release?

### ISSUE THREAD

**Issue by Paul-E** [mitsuhiko/redis-rs#363]
I would like to use the changes in #321 (which fixes a regression), and using the github repo URL is not an option. It has been some time since the last release. Would it be possible to publish a new release?

**Comment by rish-onesignal** [comment]
We would also like a new release to get the changes in https://github.com/mitsuhiko/redis-rs/pull/344

**Comment by Paul-E** [comment]
@badboy ?

**Comment by badboy** [comment]
Thanks for the ping, I'll take care of that (it will need to wait another day though).

**Comment by badboy** [comment]
Done. v0.17.0 is out

**Comment by Paul-E** [comment]
Thank you!
