### ISSUE TITLE
get tokio connection manager hangs when cannot connect

### ISSUE THREAD

**Issue by kbacha** [mitsuhiko/redis-rs#392]
We ran into an issue where the network was a tarpit due to bad security groups in AWS. The connect never returns and our server hung while awaiting it. Would it be possible to add a connect timeout here so that we can fail earlier and be aware of the failing connection?

**Comment by zopu** [comment]
I'm hitting a similar issue that seems to have just popped up. Did behaviour here recently change and cause Client::get_tokio_connection_manager to block on the connection being established (or timeout)?

**Comment by Marwes** [comment]
> I'm hitting a similar issue that seems to have just popped up. Did behaviour here recently change and cause Client::get_tokio_connection_manager to block on the connection being established (or timeout)?

@zopu Nothings changed to my knowledge, if you think there has please indicate which versions you find a difference with.

@kbacha 
Generally you can just wrap your future with `tokio::time::timeout` (or equivalent). I don't think redis-rs should or needs to add an option for this.

**Comment by zopu** [comment]
Wasn't aware of tokio::time::timeout, thanks!

I started noticing timeouts in the build of my code this morning. I'm only seeing this on my (os x) dev machine, but not on my linux CI. If I can pin this down to a change in the lib vs something wrong with my client, I'll report back.

**Comment by kbacha** [comment]
@Marwes The timeout solution works great in my use case, as I can use it to panic and exit! Thank you.
