### ISSUE TITLE
Async connection timeout?

### ISSUE THREAD

**Issue by Luminoth** [mitsuhiko/redis-rs#395]
I've been curious lately about what the correct response to a hung async connection should be and was hoping I could get some tips on the expected way to handle it. For reference, my test scenario is an app that updates a key every 15 seconds using the aio ConnectionManager. I've observed that if I pause my redis server with SIGTSTP, instead of the connection dying the redis requests just hang forever. Knowing that this is something that could happen (a connection that stops responding but doesn't drop), is the correct way to handle it to wrap each command call in something like a tokio Timeout? I'm not super sure what the effect of doing that would actually be if I keep re-using the same connection after a timeout occurs.

**Comment by Luminoth** [comment]
```
#[inline]
pub fn redis_error_from_elapsed(_: tokio::time::Elapsed) -> redis::RedisError {
    redis::RedisError::from(io::Error::from(io::ErrorKind::TimedOut))
}

#[inline]
pub async fn timeout_cmd<T>(
    duration: Duration,
    future: redis::RedisFuture<'_, T>,
) -> redis::RedisResult<T> {
    timeout(duration, future)
        .await
        .map_err(redis_error_from_elapsed)
        .and_then(|v| v)
}
```

is what I've come up with if https://github.com/mitsuhiko/redis-rs/pull/397 isn't likely to merge in. It's still error prone if a call is missed, but it seems to do the trick outside of that.

**Comment by Marwes** [comment]
If you really want to guard all commands you should be able to implement `ConnectionLike` on your own for a wrapper.

```rust
struct TimeoutConnection<C> {
    con: C,
    timeout: Duration,
}

impl<C: ConnectionLike> ConnectionLike for TimeoutConnection<C> {
}
```

**Comment by Luminoth** [comment]
That worked perfectly! If it's of any use to anyone else, the full implementation I went with on that is this:

```
#[derive(Clone)]
pub struct TimeoutConnection<C> {
    con: C,
    timeout: Duration,
}

impl<C> TimeoutConnection<C> {
    pub fn new(con: C, timeout: Duration) -> Self {
        Self { con, timeout }
    }
}

impl<C: ConnectionLike + Send> ConnectionLike for TimeoutConnection<C> {
    fn req_packed_command<'a>(
        &'a mut self,
        cmd: &'a redis::Cmd,
    ) -> redis::RedisFuture<'a, redis::Value> {
        (async move {
            timeout(self.timeout, self.con.req_packed_command(cmd))
                .await
                .map_err(|_| redis::RedisError::from(io::Error::from(io::ErrorKind::TimedOut)))
                .and_then(|v| v)
        })
        .boxed()
    }

    fn req_packed_commands<'a>(
        &'a mut self,
        cmd: &'a redis::Pipeline,
        offset: usize,
        count: usize,
    ) -> redis::RedisFuture<'a, Vec<redis::Value>> {
        (async move {
            timeout(
                self.timeout,
                self.con.req_packed_commands(cmd, offset, count),
            )
            .await
            .map_err(|_| redis::RedisError::from(io::Error::from(io::ErrorKind::TimedOut)))
            .and_then(|v| v)
        })
        .boxed()
    }

    fn get_db(&self) -> i64 {
        self.con.get_db()
    }
}
```
