### ISSUE TITLE
Upgrade to tokio 0.3

### ISSUE THREAD

**Issue by djc** [mitsuhiko/redis-rs#396]
Would be nice to have.

**Comment by vipera** [comment]
I just took a quick look, and it looks like Marwes/combine#302 would have to be addressed first, as that's a Tokio 0.2 dependency.

**Comment by djc** [comment]
Yes, I came to the same conclusion when I was looking at this.

**Comment by Austaras** [comment]
But combine has a feature flag for tokio 0.3?

**Comment by djc** [comment]
(Looks like this is being fixed over in #405.)

**Comment by RAnders00** [comment]
Combine now has tokio 0.3 support in v4.4.0.

**Comment by nazar-pc** [comment]
Well, now #378 didn't arrive in 0.17.x, but 0.18.x is incompatible with Tokio 0.2 that Actix uses :disappointed:

**Comment by Marwes** [comment]
You can use https://github.com/LucioFranco/tokio-compat-02/ to use tokio 0.2 and 0.3 simultaneously @nazar-pc

**Comment by nazar-pc** [comment]
Only works the other way around unfortunately. There is an issue in Actix about upgrading to 0.3, will use a git commit that includes above fix for the time being.
