### ISSUE TITLE
Connection should not be closed for valid error responses

### ISSUE THREAD

**Issue by gavrie** [mitsuhiko/redis-rs#398]
The following code fails due to the connection being closed upon any `ERR` response from Redis:

```
#[test]
fn test_error_disconnect() {
    let client = redis::Client::open("redis://127.0.0.1:6379/").unwrap();
    let mut con = client.get_connection().unwrap();
    let res: redis::RedisResult<()> = redis::cmd("set").arg("x").query(&mut con);
    res.expect_err("should fail");
    let _: () = redis::cmd("get").arg("x").query(&mut con).unwrap();
}
```

The `set x` command is missing an argument, and therefore Redis returns the error `ERR wrong number of arguments for 'set' command`.

Running this with `cargo tests` results in:
```
thread 'test_error_disconnect' panicked at 'called `Result::unwrap()` on an `Err` value: Broken pipe (os error 32)', tests/error-disconnect.rs:9:60
```

The connection is being closed after the error result. The code in `connection.rs` says:
```
        // shutdown connection on protocol error
        if let Err(e) = &result {
            let shutdown = e.kind() == ErrorKind::ResponseError
                || match e.as_io_error() {
                    Some(e) => e.kind() == io::ErrorKind::UnexpectedEof,
                    None => false,
                };
```

So, when a protocol error is returned by the server, the connection is closed by the client. This _might_ make sense for certain kinds of low level errors, but for a simple and valid error like the above one it's certainly unexpected.

Other clients such as `redis-py` do not behave this way.

I would have expected the connection to remain open upon this valid error response.

The problem is the following code in `parser.rs`:
```
                    let kind = match pieces.next().unwrap() {
                        "ERR" => ErrorKind::ResponseError,
```

It doesn't make sense to me that a general `ERR` response like this one is treated as a protocol error.

The suggested fix would be to explicitly handle the `ERR wrong number of arguments` error and give it its own kind. This would be in line with the Redis module API that has `RedisModule_WrongArity` especially for this error.

Fixing this would both remove this element of surprise for people used to other clients, and make it much easier and cleaner to write test code that expects errors for specific scenarios (which is how I encountered the issue in the first place).

**Comment by Terkwood** [comment]
Great find.  This sounds like a nice plan

**Comment by npajkovsky** [comment]
I have found it too, and I have proposed fix.

https://github.com/mitsuhiko/redis-rs/pull/423/commits/c51c22e719c4402afdd45c33d8b24e5e27aef837

**Comment by npajkovsky** [comment]
Should be closed, patch has been merge.
