### ISSUE TITLE
AUTH command fails when username is specified in the connection URL for Redis v5 (and possibly lower)

### ISSUE THREAD

**Issue by gyfis** [mitsuhiko/redis-rs#406]
Hi,

I encountered an error where I have a redis connection URL in this format: `redis://user:password@127.0.0.1:6379` and the AUTH command fails.

My redis is version 5.0.7, and this connection string doesn't go through - fails on AUTH. Since there is no notion of user in redis v5 or lower, the username should be ignored; however, the code currently always sends the username to redis.

It'd be great if this lib could recognize which redis is currently being run, and if v5 or lower, send proper AUTH command with no username (I didn't find a reference to the redis version currently, though).

This is the code snippet that currently always sends the username:
```
    if let Some(passwd) = &connection_info.passwd {
        let mut command = cmd("AUTH");
        if let Some(username) = &connection_info.username {
            command.arg(username);
        }
        match command.arg(passwd).query::<Value>(&mut rv) {
            Ok(Value::Okay) => {}
            _ => {
                fail!((
                    ErrorKind::AuthenticationFailed,
                    "Password authentication failed"
                ));
            }
        }
    }
```

Let me know if I can give more debug info; thanks!

**Comment by weihanglo** [comment]
Hmm.... 🤔 I think it is fair to reject unnecessary username input to align to behavior of old version of Redis. Below is the behavior of Redis 4.0 when passing two arguments to the `AUTH` command.  

```console
127.0.0.1:6379> AUTH username password
(error) ERR wrong number of arguments for 'auth' command
```

Just curious, what's your scenario of passing username to Redis lower than v5?

**Comment by gyfis** [comment]
@weihanglo Thanks for the reply! I think it'd also makes sense because `redis-cli` for Redis below 6.0 ignores the username in URL as well when passed as an argument `-u`.

As for the scenario - I'm using [dokku/dokku](https://github.com/dokku/dokku) with the [dokku/dokku-redis](https://github.com/dokku/dokku) plugin, and they fill a username incorrectly to the URL. I added a [pull request](https://github.com/dokku/dokku-redis/pull/157) with a fix there, though I'm not sure when it will be merged. I'm able to overwrite the env variable they are setting, but I wanted this library to handle it too, when it encounters this in the future.

**Comment by npajkovsky** [comment]
Well, that's easy to solve. And you were almost there

```
       if let Some(username) = &connection_info.username {
            command.arg(username);
        }
```
`connection_info` defines `username` as an `Option<String>` and that means, you can omit the value.
Just simply use connection string without username`redis://:password@127.0.0.1:6379`.

**Comment by gyfis** [comment]
@npajkovsky thanks for the comment! Indeed, I removed the username from the connection URL and it works as expected, but I'd be more happy for this to be supported directly in the lib :)

**Comment by npajkovsky** [comment]
@gyfis I don't think, it's doable. You have to send AUTH, before you can get redis server version. With TLS you have even more problems.

**Comment by gyfis** [comment]
@npajkovsky The most straightforward fix would be to rescue on `(error) ERR wrong number of arguments for 'auth' command` and try going with `AUTH password` only, which seems like a fair fallback to me.

**Comment by npajkovsky** [comment]
Should be closed, patch has been merge.
