### ISSUE TITLE
0.18 Release

### ISSUE THREAD

**Issue by dbrgn** [mitsuhiko/redis-rs#418]
I noticed that version 0.18 was released, and came here to check the changelog. However, the changelog doesn't mention 0.18 and there's no "version bump" or "release 0.18" commit in the history either.

I then found the 0.18 tag here: https://github.com/mitsuhiko/redis-rs/commit/d5fc4242e8e6bd3584506c26c37bb31f1b8a0949 However, it's a commit that doesn't belong to any branch.

@Marwes maybe you forgot to push some commits? Would be nice to get an up to date changelog on the master branch :slightly_smiling_face:

**Comment by Marwes** [comment]
Forgot to merge #412 ! Fixed now
