### ISSUE TITLE
Help: Is it possible to get the response in the raw RESP format? 

### ISSUE THREAD

**Issue by AjithPanneerselvam** [mitsuhiko/redis-rs#420]
Hi, 

I'm writing a proxy for Redis. I need the response from Redis client in the RESP format in bytes. I see all the APIs are returning the response in a high-level data structure (type `Value`). Is there any way to get the Redis server response as raw bytes without any translations?

**Comment by Marwes** [comment]
I think it would be hard to expose an API for that purpose, I would implement my own client for the proxy for that usecase, possibly only using the encoder/decoder part from redis-rs.

**Comment by AjithPanneerselvam** [comment]
Oh, got it. Thanks @Marwes!
