### ISSUE TITLE
4.5.0 causing compile error in redis-rs 0.19.0

### ISSUE THREAD

**Issue by TheGlenn88** [mitsuhiko/redis-rs#429]
```rust
error[E0433]: failed to resolve: use of undeclared crate or module `bytes_05`
   --> /Users/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/combine-4.5.0/src/stream/buf_reader.rs:419:6
    |
419 | impl bytes_05::BufMut for Bytes05<'_> {
    |      ^^^^^^^^ use of undeclared crate or module `bytes_05`

error[E0433]: failed to resolve: use of undeclared crate or module `bytes_05`
   --> /Users/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/combine-4.5.0/src/stream/buf_reader.rs:606:26
    |
606 |     fn poll_write_buf<B: bytes_05::Buf>(
    |                          ^^^^^^^^ use of undeclared crate or module `bytes_05`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `combine`
```

**Comment by TheGlenn88** [comment]
never mind, closing this issue, it seems it's an issue with mobc-redis causing the compile error

**Comment by eyalsatori** [comment]
Hi, 
I am suffering from the same error , 
could you explain what you mean by   `it's an issue with mobc-redis causing the compile error` ? 
(The mobc-redis not appears in my cargo tree )

**Comment by eyalsatori** [comment]
Ok, 
my problem was that i used the `tokio-rt-core` feature , that supported until 0.17.0 version ,

**Comment by eyalsatori** [comment]
well , my problem was that i used `tokio-rt-core` that supported until 0.17 - so my app stuck with that version,
when i switched to `tokio-comp` i was able to upgrade 0.19 , and then it's compiled with combine 4.5

**Comment by TheGlenn88** [comment]
Oops, I thought i put this on the combine repo.

Yes thanks for pointing that out, my goal is to get to redis 0.19, but have a couple of packages holding me back, mobc/mobc-redis I can't update until actix-rt  update to tokio v1, looking at their PR's and discord it's a big job.

Dependency management is like https://www.youtube.com/watch?v=AbSehcT19u0
