### ISSUE TITLE
Is it possible  now to run redis with tokio 0.* ?   

### ISSUE THREAD

**Issue by eyalsatori** [mitsuhiko/redis-rs#431]
Hi , 

I have app that using Tokio 0.2.9 ,  and redis . 

The app redis version of the app was set to `=0.17.0`. 

But the problem is that in `cargo.toml` of  `0.17.0` the version of the lib "combine" was set to 4.4 , and when 4.5 released `cargo update`  updated  to the 4.5 version. When i try to compile "redis" `0.17.0` with  "combine" 4.5 is give compilation error(see issue #429 ). 

For that reason i can't use the 0.17.0 version of Redis, and must use the 0.19  - but the in 0.19  it's  uses  Tokio 1.0 , what will require a lot of changes for my app - and probably will conflict with other libs that i am using.       

any help would be appreciated.  
(I think that even 0.17.1 version -that will set the version of combine to `=4.4` will do the work  )

**Comment by Marwes** [comment]
This is fixed in combine 4.5.1
