### ISSUE TITLE
Password authentication fails, succeeds with redis-cli

### ISSUE THREAD

**Issue by x04** [mitsuhiko/redis-rs#447]
I am trying to connect to an authenticated redis server with redis-rs and attempting to open a connection fails with "Password authentication failed."

Password is alphanumerical, it contains no special characters, even though it shouldn't matter if it did according to some closed issues I've read.

```rust
fn main() -> Result<(), redis::RedisError> {
    let conn_info = "redis://username:password@redislabs.com:1234".into_connection_info()?;
    println!("{:?}", conn_info);
    let rc = redis::Client::open("redis://username:password@redislabs.com:1234")?;
    rc.get_connection()?;
    Ok(())
}
```

![image](https://user-images.githubusercontent.com/19847095/106178308-9b4d6b00-6167-11eb-8d7f-12edbac1bd72.png)

To show that the URL is valid:

![image](https://user-images.githubusercontent.com/19847095/106177838-064a7200-6167-11eb-92e3-86eeca613713.png)

**Comment by x04** [comment]
Nevermind, it appears the server is using an earlier version of redis.

**Comment by kotx** [comment]
> Nevermind, it appears the server is using an earlier version of redis.

What version does redis-rs use?
