### ISSUE TITLE
TIME_WAIT sockets

### ISSUE THREAD

**Issue by nappa85** [mitsuhiko/redis-rs#454]
I'm testing redis-rs alone and with various pooling systems, not r2d2 because I need async/await, but bb8, deadpool and mobc.
I've noticed that with every operation, a socket TIME_WAIT is created beside the ESTABLISHED one, like if the socket is discarded and recreated every time.
With bb8, using a min_idle > 0, this is even worse, because after every single operation, the number of TIME_WAIT sockets created is the same of the number of the idle connections.
Having the same behavior on every pooling system, I think this is a redis-rs issue, and I fear that, with high request rates, I'll end up saturating available sockets.

I'm seeing the TIME_WAIT sockets with `netstat -npa | grep 6379` where 6379 is redis port in use.

**Comment by Marwes** [comment]
This seems like an issue with the pooling crates, not redis-rs? I don't understand what you expect this crate to do about this.

**Comment by nappa85** [comment]
Yes, you're right, trying to demonstrate the problem I ended up writing a working pooling crate that doesn't have the described problem: https://github.com/nappa85/redis_dumbpool

I'm closing the issue, sorry for having made you waste time
