### ISSUE TITLE
Provide fake connection for testing?

### ISSUE THREAD

**Issue by mlh758** [mitsuhiko/redis-rs#455]
I wrote a basic in-memory fake for the `AsyncCommands` trait. It's been a nice way to pass this to my functions and make sure they're collecting the correct types and such.

[Here is the implementation](https://github.com/mlh758/resque-web-ish/blob/629f84b63750ac8498d478a645c0d709a8ff7364/src/resque/tests/mock_redis.rs). Is this something that you would be interested in having as part of the redis-rs library itself? I understand not wanting to take on maintenance for it, but I think it could be helpful for other people writing tests so I thought I'd ask.

**Comment by tdyas** [comment]
I wrote something similar as well although focused on `ConnectionLike`. PR here: https://github.com/mitsuhiko/redis-rs/pull/465

**Comment by mlh758** [comment]
My implementation is for `ConnectionLike`, that's definitely the easiest way to get `Commands`. On your PR, [this](https://github.com/mlh758/resque-web-ish/blob/629f84b63750ac8498d478a645c0d709a8ff7364/src/resque/mod.rs#L250) is how you can test a pipeline with a mock `ConnectionLike` implementation.

**Comment by mlh758** [comment]
Going to close this though, it hasn't gotten any comments from maintainers and your PR is sitting open too.
