### ISSUE TITLE
One element array as keys with HGET strange problem

### ISSUE THREAD

**Issue by dgr113** [mitsuhiko/redis-rs#457]
**Use case:**
I get field names from my configuration file.
This can be an array of strings of any length.

But if vector/slice consists of a single element, then this sometimes causes type inference problems in result.
I want to get a vector of strings in the response, but output is... string type.

As a result, I get an empty array, probably as a compromise (but useless) result for me.

```rust
let all_keys: Vec<String> = conn.keys("*") ?;

let fields = &["status", "_"];  // This works fine
// let fields = &["status"];  // But this wrong for result type!

let mut results = vec![];
for k in &all_keys {
    if let Ok(t) = conn.hget::<_, _, Vec<String>>(k, fields) {
        results.push( t );
    }
}

println!("RESULTS {:?}", &results);
```

Problems only occur when using a high-level interface. So sometimes I have to do like this:
```rust
fn _comm_append_args<'a, T>(comm: &'a mut Cmd, key: &'a str, args: &'a [T]) -> &'a mut Cmd
    where T: Into<String> + ToRedisArgs + Display
{
    let mut wrapped_comm = comm.arg( key );
    for arg in args {
        wrapped_comm = wrapped_comm.arg( arg.to_string() );
    }
    wrapped_comm
}
```
Doesn't look very cool ? But at least it works in my service code...

In general, I observe a lot of very strange problems with empty strings turning into nothing. 
Now I'm trying to reproduce it ;)

**Comment by saskenuba** [comment]
I have the same issue with version `0.17`. Querying with vectors of length 1 doesn't return a vector with a key of length 1, but instead a string type.

Sample: 
```rust

let length_one_vec = vec![1];

let recovered_keys: Vec<String> = redis_connection
        .clone()
        .hget(user_inventory_key, length_one_vec)
        .await?;
```

`Response was of incompatible type: \"Response type not vector compatible.\" (response was string-data('\"normalfield-testedNova | Predator\"'))",`

**Comment by saskenuba** [comment]
I am not running into this issue on `0.21` anymore. Seems solved!
