### ISSUE TITLE
Unable to use async-commands with `redis::aio::ConnectionManager`

### ISSUE THREAD

**Issue by curiousdev** [mitsuhiko/redis-rs#460]
I'm reviewing the documentation and struggling to understand how to properly use `ConnectionManager` in the context AsyncCommands. What am I overlooking? 

```
let client = redis::Client::open("redis://.....").unwrap();
let mgr = redis::aio::ConnectionManager::new(client).await.unwrap();
```

```
#[get("/status")]
pub async fn health(state: Data<AppState>) -> Result<HttpResponse, Error> {
    info!("Verifying connectivty to redis cluster.");

    let mut conn_mgr = &state.conn_mgr;

    let result : RedisResult<Option<String>> = redis::cmd("PING").query_async(&mut conn_mgr).await;

...
}
```

Here's error, I'm trying to fix
```
let result : RedisResult<Option<String>> = redis::cmd("PING").query_async(&mut conn_mgr).await;
                                                                               ^^^^^^^^^^^^

                                                                               the trait `redis::aio::ConnectionLike` is not implemented for `&ConnectionManager`
                                                                               help: consider removing the leading `&`-reference
```

Using these features
```
redis = { version = "0.20.0", features = ["connection-manager", "tokio-comp", "aio"] }
```

**Comment by curiousdev** [comment]
`ConnectionManager` implements `ConnectionLike` trait which is required by `query_async()`

**Comment by scooter-dangle** [comment]
I might be missing something, and I'm not familiar with `Data<T>`, but you need to pass a mutable reference to the `ConnectionManager`  (`&mut ConnectionManager`) to `query_async`. Right now, you appear to be passing a mutable reference to a reference to the `ConnectionManager` (`&mut &ConnectionManager`).

Are you able to modify your code to something like the following?
```rust
#[get("/status")]
pub async fn health(mut state: Data<AppState>) -> Result<HttpResponse, Error> {
    info!("Verifying connectivty to redis cluster.");

    let result : RedisResult<Option<String>> = redis::cmd("PING").query_async(&mut state.conn_mgr).await;

    // ...
}
```

**Comment by mlh758** [comment]
The connection manager can be cloned [docs](https://docs.rs/redis/0.20.0/redis/aio/struct.ConnectionManager.html). You'll still have the same underlying connection but it multiplexes requests through the one connection.

[Here](https://github.com/mlh758/resque-web-ish/blob/master/src/handlers.rs#L55) is an example of doing this with Actix.

**Comment by curiousdev** [comment]
@mlh758 thank you for you confirming this!
