### ISSUE TITLE
Having occasionally `Err` - An error was signalled by the server: 15916

### ISSUE THREAD

**Issue by ozer** [mitsuhiko/redis-rs#467]
Hi everyone,

Firstly, thanks heaps to people contributed this repo! 🙂 

I'm trying to rewrite one of our services in Rust and we had some data stored on clustered AWS ElastiCache. I need to have a pool and I could not use Cluster Support with pool libraries I mentioned in the below.

I occasionally receive the error above when I run GET command. I don't think my custom data type has an issue as it actually works. I also noticed that when I kill the app and re-run, it fails with this error most of the time.

I've had this issue with `bb8` and `mobc` pool solutions as well. Hence, I thought the root cause of the issue might be related to this repository.

Do you have any idea what actually could be happening and how I can fix this? How can I get more information around what's happening?

```
#[derive(Serialize, Deserialize, Debug)]
pub struct MemberId(i32);

impl MemberId {
    pub fn new(id: i32) -> Self {
        Self(id)
    }
}

impl FromRedisValue for MemberId {
    fn from_redis_value(v: &RedisValue) -> RedisResult<Self> {
        let formatted = format!("{:?}", v);
        let x: String = formatted.chars().filter(|v| v.is_digit(10)).collect();
        let id: i32 = x.parse().unwrap();
        Ok(MemberId::new(id))
    }
    
    fn from_redis_values(_items: &[RedisValue]) -> RedisResult<Vec<Self>> {
        unimplemented!()
    }

    fn from_byte_vec(_vec: &[u8]) -> Option<Vec<Self>> {
        unimplemented!()
    }
}

let member_id: Option<MemberId> = cmd("GET").arg(member_cache_key).query_async(&mut *redis_connection).await.unwrap();
```

Thanks,

**Comment by Marwes** [comment]
Afraid I don't understand what the error is, it would help if you posted the exact error message and provided a reproduction, ideally standalone such that I could just copy pasted it into a `#[test]` for the test-suite.

The `from_redis_value` implementation looks rather suspicious though, debug formatting a `RedisValue` and the parsing out the filtered digits is going to be brittle.

**Comment by ozer** [comment]
Hey @Marwes , thank you so much for your comment.

I don't understand neither although, I tried to debug it. It's just a weird error thrown at some point. I understand the implementation of `FromRedisValue` seems suspicious, I reckon it doesn't have anything to do with this error. It throws the error before it even reaches there. 😞 

What makes it hard to reproduce is that I am not always getting this error and, it only happens when I try to connect our Clustered AWS ElastiCache.

Even in the times it works with AWS ElastiCache, as the time it starts to receive like 10-15 requests per second, it starts to fail again...

The actual error thrown when I send `get` command is:
```
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: An error was signalled by the server: 15916 x.x.x.x:6379
```

I can provide the code below:

I am using `Actix-Web Backend` for my micro service. I need to have a Redis connection pool so, I tried both `bb8` and `mobc`, I was still getting the error without using these pools.
```
..
use mobc::Pool as RedisPool;
use mobc_redis::{redis::{aio::Connection as RedisAsyncConnection, Client as RedisClient, cmd, FromRedisValue, RedisResult, Value as RedisValue}};
use mobc_redis::RedisConnectionManager;
..

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let redis_client = RedisClient::open("redis://elasticache.x.x.x").unwrap();
      let manager = RedisConnectionManager::new(redis_client);
      let redis_pool = RedisPool::builder()
          .max_idle(15)
          .max_open(50)
          .build(manager);
          
    let arc_redis_pool = web::Data::new(redis_pool.clone());
    
    HttpServer::new(move || {
          App::new()
              .route("*", web::to(index))
              .app_data(settings_data.clone())
              .app_data(arc_redis_pool.clone())
              .app_data(sqlx_pool.clone())
              .app_data(gateway_client.clone())
      })
          .listen(listener)?
          .run()
          .await
}

async fn index(app_data: web::Data<Settings>,
               redis_pool: web::Data<RedisPool<RedisConnectionManager>>,
               pg_pool: web::Data<SqlxPool<Postgres>>,
               gateway_client: web::Data<ReqwestClient>,
               _req: HttpRequest) -> Result<HttpResponse, GatewayException> {

..
    let mut redis_connection = redis_pool.get().await.unwrap();
    // this is the line I am occasionally getting the error.
    let member_id: Option<MemberId> = cmd("GET").arg(member_cache_key).query_async(&mut *redis_connection).await.unwrap(); 
}

```

**Comment by Marwes** [comment]
If you are using a clustered redis server you need to use https://github.com/Marwes/redis-cluster-async for async queries, I haven't had time to merge it back into redis-rs proper (like the sync support that was merged a while back).

The error doesn't say much though, so it may not help still.

**Comment by ozer** [comment]
Thanks a lot for your help. I'll be looking into it :)

**Comment by govo** [comment]
Got the same error, any new progress?

**Comment by govo** [comment]
I am using AWS Redis, when turn more than 1 node, this error happens. when cut the nodes to 1, things work find.

With AWS Redis 6.2

**Comment by mohitreddy1996** [comment]
@govo we are seeing something similar. Did you get around fixing this by any chance?

**Comment by jaymell** [comment]
It sounds like you could be using a non-clustered connection in a clustered scenario?
