### ISSUE TITLE
Question: Handling interrupted Connections properly

### ISSUE THREAD

**Issue by raymontag** [mitsuhiko/redis-rs#48]
Hey,

I wondered what happens with a redis::Connection if the connection to Redis was interrupted somehow, e.g Redis-server is not available. Do I need to create a new redis::Connection or can I use the old instance? What's the proper way to handle this?

**Comment by mitsuhiko** [comment]
You need to create a new connection as the connections are stateful.  We should probably start to investigate tcp keepalive values.

**Comment by raymontag** [comment]
Ok, thanks :)
