### ISSUE TITLE
Is a Cloneable Multiplexed PubSub Connection possible?

### ISSUE THREAD

**Issue by kennetpostigo** [mitsuhiko/redis-rs#484]
Hi 👋,

I'm using redis as a broker in my application, and I have a PubSub connection using `redis::aio`. I'm running into case where because PubSub doesn't implement `Clone` I need to wrap it in a `Arc<RwLock<PubSub>>`. However since i'm preserving a connection and only 1 writer is allowed at once by `RwLock` the lock is held by the first pubsub connection until that client is disconnected and no messages are sent by subsequent pubsub connections while that connection is alive/active. I'm currently using the `async` features specifically the `async_std` runtime, not sure if that matters.

How do you all get around this given that multiplexed connections don't support being turned `.into_pubsub()`? Some code might help illustrate the problem i'm having:
```rust
// Waits for the ability to obtain the write lock.
// pubsub is: client.get_async_std_connection().await?.into_pubsub();
let mut pubsub = req.state().pubsub.write().await;

pubsub.subscribe("users").await?;
pubsub.subscribe("channels").await?;
pubsub.subscribe("messages").await?;

let mut combined_stream = futures_util::stream::select(
  wsc.clone().map(Either::Left),
  pubsub.on_message().map(Either::Right),
);

// Here we hold the write lock until the websocket connection is disconnected
while let Some(message) = combined_stream.next().await {
  // here we listen for messages coming in from the websocket connection and use the
  // pubsub stream to broadcast it to all rust app instances listening to pubsub stream.
  // What goes on:
  // Websocket recieves msg -> 
  // sends message to redis pubsub ->
  // redis broadcasts it and then uses websocket connection handle to send back to the client
}

Ok(())
```

I'm not sure how to get around this, does anyone have advice for how to work around this problem? If this isn't possible because of the implementation of PubSub at the moment, does anyone know what needs to be added/changed? (I'm a rust newbie but would be glad to try to contribute to make this possible)

**Comment by kennetpostigo** [comment]
I just found that I can clone `MultiplexedConnection`, however, that doesn't have `.into_pubsub()`. Is there a way around that?

**Comment by enzious** [comment]
Nope, I believe once a connection is pubsub, it can only be pubsub.

**Comment by extrawurst** [comment]
yeah I am simply connecting twice to my redis server to be able to subscribe and do other stuff at the same time

**Comment by kennetpostigo** [comment]
@enzious , yea I get that, but I'm more so interested if there is anyway to make a pubsub connection instance clone-able/share-able. It would be particularly useful for me, so I wouldn't have to create a local connection for every individual client.

**Comment by kennetpostigo** [comment]
@extrawurst I'm currently keeping 2 connections open, a pubsub connection and a regular multiplexed connection. I believe that in itself is completely fine. My particular pain point is that a pubsub connection isn't clone-able. I don't want to instantiate a connection per client, I would prefer to just clone an existing pubsub connection, than create a new pubsub connection per connected client.

Please let me know if i'm not explaining well, I can try again

**Comment by Marwes** [comment]
Having a cloneable `PubSub` would be possible but it would be a wrapper around a channel or mutex for synchronization so I don't think it gives you much over doing that manually (providing it in redis-rs could imply it is more efficient than doing the synchronization manually so I am not a fan of that).

**Comment by kennetpostigo** [comment]
@Marwes Yea, I understand, just thought that it might help remove boilerplate from the user side, but it makes sense.

Thank you @Marwes @extrawurst @enzious
