### ISSUE TITLE
Not clear which git commit corresponds to 0.20.1 and no CHANGELOG entry

### ISSUE THREAD

**Issue by jbg** [mitsuhiko/redis-rs#491]
We're trying to debug sudden excessive CPU usage of an async service that is using the `redis` crate, which seems to only be occurring after updating to 0.20.1. However, there's no tag for the version nor any commit message from cargo-release as there was with 0.20.0. There's also no CHANGELOG entry for 0.20.1. Which commit corresponds to 0.20.1?

**Comment by jbg** [comment]
Hmm, `Cargo.toml` in the repository still has `version = "0.20.0"`. Is the 0.20.1 release on crates.io legitimate?

**Comment by jbg** [comment]
I managed to verify that 0.20.1 on crates.io corresponds to [this commit](https://github.com/mitsuhiko/redis-rs/commit/9b6f35dad8e865e5abee3c429be770b4b9e08517) which is present in the repository but not associated with any branch, and it contains all changes currently present on the `master` branch.

We also verified that rolling back to 0.20.0 seems to fix our high CPU usage issue.

**Comment by Marwes** [comment]
Fixed, had a permissions issue when pushing the version update as I am juggling two github accounts.

**Comment by Marwes** [comment]
If you manage to get a reproduction for the performance issue feel free to open a new issue

**Comment by jbg** [comment]
We can consistently reproduce the performance issue on 0.20.1 and not on 0.20.0, but we are having trouble minimising it. What are the changes in 0.20.2?

**Comment by Marwes** [comment]
It was probably fixed in 0.20.2 https://github.com/mitsuhiko/redis-rs/issues/488
