### ISSUE TITLE
Issue while accessing Different database within redis

### ISSUE THREAD

**Issue by hareendran** [mitsuhiko/redis-rs#50]
i was trying to access a different database on redis, but the code just exits. no panics no exceptions whatsover. 

could you please help me out in figuring out what would be the issue?
I have put the gist under my repository..
https://github.com/hareendran/redis_rust_with.git

**Comment by mitsuhiko** [comment]
I'm not sure, don't have the time to debug the issue but as far as I can tell selecting different databases works just fine.  That being said: database numbers are a deprecated feature in redis.

**Comment by badboy** [comment]
Well, it's not "officially" deprecated and won't be removed for quite some time.

**Comment by harrydevnull** [comment]
Issue with acessing non default db was resolved once the shep.master pull request was merged in.
