### ISSUE TITLE
0.21 fails compilation with default-features = false and tokio-comp enabled

### ISSUE THREAD

**Issue by djc** [mitsuhiko/redis-rs#515]
```rust
error[E0432]: unresolved import `futures_util::Stream`
 --> /Users/djc/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-0.21.0/src/cmd.rs:4:16
  |
4 |     FutureExt, Stream,
  |                ^^^^^^
  |                |
  |                no `Stream` in the root
  |                help: a similar name exists in the module (notice the capitalization): `stream`
```

Maybe `tokio-comp` should also enable `streams`, or some `tokio-comp`-conditional items should also depend on `streams`?

(This broke bb8-redis.)

**Comment by kuy** [comment]
@djc Hi, I also faced the same issue with you. I resolve it by updating a specific dependency. Try run `cargo update -p futures-util --precise 0.3.15` command from your project that has a dependency of `redis-rs` crate.

**Comment by djc** [comment]
If that's a requirement than redis should probably depend on futures-util 0.3.15 instead of 0.3.0.
