### ISSUE TITLE
password can't support # 

### ISSUE THREAD

**Issue by figo361** [mitsuhiko/redis-rs#517]
when i set password have # symbol ,will get this error :
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Redis URL did not parse',

**Comment by tomers** [comment]
You need to encode the password that is set in the connection info URL. See examples in:
https://github.com/mitsuhiko/redis-rs/pull/522/files
```
❯ python3 -c "from urllib.parse import quote; print(quote('/mypass#/+ word=$+', safe=''))"
%2Fmypass%23%2F%2B%20word%3D%24%2B
```

**Comment by tomers** [comment]
Rust code:
```
use urlencoding::encode;

...

    fn get_connection_info(redis_password: &str, redis_host: &str, redis_port: &str) -> String {
        format!(
            "redis://:{}@{}:{}/",
            encode(redis_password),
            redis_host,
            redis_port
        )
    }
```

**Comment by figo361** [comment]
oh，thanks you ..

**Comment by zhiburt** [comment]
@tomers thanks as well

A little note about your code.

use `rediss` scheme if you're using redis over TLS

Spend some time to figure this thing out :sweat_smile:
