### ISSUE TITLE
Error when querying redis to get ordered set data

### ISSUE THREAD

**Issue by dzobbe** [mitsuhiko/redis-rs#53]
Hi,
I was trying to query redis to get an ordered data set. I used the "zrangebyscore_withscores" function and it gives me this error.:

e ->Response was of incompatible type: "Response type not convertible to numeric." (response was bulk(string-data('"400.4"'), string-data('"1437421736000"'), string-data('"33.4"'), string-data('"1437420523000"')))

Am I doing something wrong??

Thanks in advance.

**Comment by badboy** [comment]
Can you show the code?
redis-rs will automatically decode the returned data to the type you specifiied. In the case of zrangebyscore this should probably be `Vec<String>`. What type did you specify?

**Comment by dzobbe** [comment]
First of all thanks for the quick response. If I specify the type for the result variable "res_str" I have a problem at compilation time. It says to me: 

    let res_str:Vec<String>=con.zrangebyscore_withscores(key, 0, 1436537637)

expected `collections::vec::Vec<collections::string::String>`,
    found `core::result::Result<_, redis::types::RedisError>`

I also tried to use the match structure to divide the correct result from the error but any time when I execute the code it goes in the error branch. 
Sorry but I don't have too much experience with Rust and I'm learning with the experience.
How do you cast the result variables?

**Comment by badboy** [comment]
There are multiple ways, depending on what you need: https://github.com/badboy/redis-zrangescore-example/blob/master/src/main.rs#L16-L29

(Oh, and I discovered a small bug writing this)
