### ISSUE TITLE
Ability to set notify-keyspace-events

### ISSUE THREAD

**Issue by Firaenix** [mitsuhiko/redis-rs#546]
I'd like to use this library to listen to redis keyspace events but wasnt able to find a way to set config at the session level like ioredis (https://github.com/luin/ioredis). 

Is this possible with this library?

**Comment by lroux-at-jellysmack** [comment]
Hello, here is an example, I react to `DEL` and `EXPIRE` keyspace events: https://github.com/Nurrl/shrekd/blob/main/src/main.rs#L79

**Comment by Firaenix** [comment]
Thank you very much, all sorted then.
