### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by Norbytus** [mitsuhiko/redis-rs#557]
I have cache server with redis as backend storage.
And I notice after many concurrent requests, server don't release the memory.
For example, I try to cache big data, and put it to that in Redis, but redis-rs don't release to OS memory.
I write simple example
OS: Manjaro 21.1.6 Pahvo
Kernel: x86_64 Linux 5.14.10-1-MANJARO
```rust
fn main() {
    let client = redis::Client::open("redis://127.0.0.1:6379").unwrap();
    let mut con = client.get_connection().unwrap();
    let data: Vec<u8> = vec![124; 26748528];
    redis::cmd("SET").arg("data").arg(data).execute(&mut con);
    let r = redis::cmd("GET").arg("data")
        .query::<Vec<u8>>(&mut con);
    drop(r);
    std::thread::sleep(Duration::new(5, 0));
}
```
I try with jemalloc, but the result is the same.
Also see different in allocation  between big and small size of data.
Heaptrack data in archive.
[heaptrack.tar.gz](https://github.com/mitsuhiko/redis-rs/files/7445849/heaptrack.tar.gz)

**Comment by tickbh** [comment]
how to fix this problem?

**Comment by BaldStrong** [comment]
@Norbytus Hello, we encountered the same issue as you. May I ask how you eventually resolved it?

**Comment by nihohit** [comment]
@BaldStrong i suggest you open a new issue, with full details of your setup, and preferably with a minimal reproducing example.
