### ISSUE TITLE
error: struct `Connection` is private

### ISSUE THREAD

**Issue by endel** [mitsuhiko/redis-rs#62]
Hi there,

I'm trying to create my own `struct` with a `redis::connection::Connection` property. Am I supposed to be able to do that?

```rust
// src/lib.rs
extern crate redis;
use redis::connection::Connection;
...
```

I'm getting the following error:

```
src/lib.rs:2:5: 2:34 error: struct `Connection` is private
src/lib.rs:2 use redis::connection::Connection;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I found this error pretty weird because the `Connection` struct [seems to be public](https://github.com/mitsuhiko/redis-rs/blob/2f328e7c1378005dd600cb354eaf00622d1e45e6/src/connection.rs#L156-L159). 

Any help is appreciated. Thank you very much!

**Comment by badboy** [comment]
It is re-exported, so you should be able to use `redis::Connection`. The `redis::connection` module itself [is not made public](https://github.com/mitsuhiko/redis-rs/blob/2f328e7c1378005dd600cb354eaf00622d1e45e6/src/lib.rs#L355), only [certain things are](https://github.com/mitsuhiko/redis-rs/blob/2f328e7c1378005dd600cb354eaf00622d1e45e6/src/lib.rs#L318-L320).

**Comment by endel** [comment]
@badboy thank you!
