### ISSUE TITLE
rpush / lpush: unable to infer enough type information about `_`

### ISSUE THREAD

**Issue by endel** [mitsuhiko/redis-rs#65]
I'm trying to do a simple `rpush` / `lpush` operation, but the compiler don't let me use strings as argument for those commands. 

```rust
use redis::{Connection, Commands};
...
self.conn.rpush("my_queue", "value");
```

Compiler error:

```
error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [E0282]
src/lib.rs:41     self.conn.rpush("my_queue", "value");
                            ^~~~~~~~~~~~~~~
src/lib.rs:41:15: 41:30 help: run `rustc --explain E0282` to see a detailed explanation
error: aborting due to previous error
```

What am I missing here?

**Comment by endel** [comment]
Actually the following `cmd` works, but `lpush` / `rpush` doesn't. Why? :cry: 

```
redis::cmd("RPUSH").arg("my_queue").arg("value").execute(&self.conn);
```

**Comment by badboy** [comment]
You need to specify the return type or call execute. 
[`rpush`](https://github.com/mitsuhiko/redis-rs//blob/master/src/commands.rs#L418-L420) simply calls the same thing you typed out, so you can actually call `execute` on it yourself, which just drops the return value or call `query` and specify a proper return type.

**Comment by endel** [comment]
@badboy thanks for your response.

Can you please provide an code example for specifying a return type or calling execute? I'm still learning the basics of rust-lang, so many basic concepts still are valuable for me.

I'm trying to use Strings as parameter:

```rust
let key = format!("{}:keyname", prefix);
let val = format!("{}", "value");
conn.rpush(key, val);
```

But the same error occurs:

```
src/lib.rs:44:15: 44:30 error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [E0282]
src/lib.rs:44     self.conn.rpush(key, val);
                            ^~~~~~~~~~~~~~~
```

**Comment by badboy** [comment]
Ah, sorry. Scratch the second part of my answer. The commands are implemented using a macro and call `query` directly.

Therefore you have to write:

```
let _ : () = con.rpush(key,val).unwrap();
```

* `_` means "don't assign to a variable, but drop directly"
* `()` is the empty value
* `unwrap()`, because it returns a `RedisResult<T>`. You should check for an error here

**Comment by endel** [comment]
@badboy thank you!
