### ISSUE TITLE
set_ex args order

### ISSUE THREAD

**Issue by doomsplayer** [mitsuhiko/redis-rs#67]
the format of setex should be `setex key expire value`
but the library uses `setex key value expire`, so calling `con.set_ex` will return `value is not an integer or out of range` error

**Comment by harrydevnull** [comment]
the implementation actually  follows the pattern ```setex key expire value```
let _ : () = try!(con.set_ex("my_key1",49,99999));
con.get("my_key1") 
yields 99999 and if you were to check on server using redis-cli you could see ```ttl``` is set to 49 initially.

**Comment by mitsuhiko** [comment]
This is fixed now.
