### ISSUE TITLE
how would we do connection pooling 

### ISSUE THREAD

**Issue by harrydevnull** [mitsuhiko/redis-rs#69]
I had couple of questions on how to use redis-rs

1. how can we use/enable connection pooling ?
2. why was connection trait exposed?

##### as in instead of using this way 
   ```let client = try!(redis::Client::open("redis://127.0.0.1/"));
    let con = try!(client.get_connection()); let _ : () = try!(con.set("my_key", 42));``` <br>
##### we could have had 
 ``` let client = try!(redis::Client::open("redis://127.0.0.1/"));
    let _ : () = try!(client.set("my_key", 42).execute()); ```  <br>



and under the hood client could borrow one connection object from the pool and once used; it could have been given back to pool.
I just wanted to understand what was the de

**Comment by badboy** [comment]
Use https://crates.io/crates/r2d2_redis ?

**Comment by harrydevnull** [comment]
@badboy thanks, to use r2d2 and redis  together, the code gets too verbose (just my opinion) . my thought was to abstract away the connection trait all together from the client; something on the lines of ```let client = try!(redis::Client::open("redis://127.0.0.1/")); let _ : () = try!(client.set("my_key", 42).execute());````
