### ISSUE TITLE
report a bug on connect

### ISSUE THREAD

**Issue by gitxpj** [mitsuhiko/redis-rs#72]
i read you source code found on connect method has wrong logic, first command must be AUTH, cause i meet a exception, there is error details: Redis server refused to switch database!

**Comment by badboy** [comment]
You're right. Care to submit a PR? You probably only need to change the order in `connect`

**Comment by gitxpj** [comment]
yeah, i want to fix that

**Comment by badboy** [comment]
Fixed by #76
