### ISSUE TITLE
Can we open a connection with a &ConnectionInfo?

### ISSUE THREAD

**Issue by dbrgn** [mitsuhiko/redis-rs#74]
I'm implementing a simple server application that can read and update some sensor values in Redis. The Redis database is being used from different Iron handlers.

Right now, I instantiate the server with a `T: IntoConnectionInfo` parameter. That makes sense, because the `ConnectionInfo` is then passed into the server instance itself.

Then I create a handler for each endpoint. Each of these handlers also needs a clone of the `ConnectionInfo`, because a handler has a `'static` lifetime bound (see http://stackoverflow.com/a/33189734/284318).

But I also have a simple helper function that retrieves a sensor value. I pass it the connection information and it then creates a `Client` and a `Connection` and returns the value.

In this case, shouldn't it be possible to simply pass in a read only reference to the `ConnectionInfo` object (`&ConnectionInfo`) instead of cloning the entire `ConnectionInfo` instance?

Right now the `Client::open` method accepts a parameter of type `T: IntoConnectionInfo`, but not a `&T: IntoConnectionInfo`.

Is this desired behavior? Am I overlooking something? (I don't have too much experience with Rust yet, so forgive me if this is a stupid question™ :smiley:)

**Comment by mitsuhiko** [comment]
Well. The client needs to hold on to it. So it would have to clone anyways.

**Comment by badboy** [comment]
@dbrgn If you want to use Redis with Iron, it's probably best to just use [r2d2-redis](https://crates.io/crates/r2d2_redis) and insert it into the chain.

**Comment by dbrgn** [comment]
@badboy wow, this is awesome! Thanks a lot for pointing me to it! :)
