### ISSUE TITLE
con.brpop always return ()

### ISSUE THREAD

**Issue by mmacedoeu** [mitsuhiko/redis-rs#75]
I am writing a rust tool to load a set from csv into a redis set on demand. I choose to "listen" for demands on redis key with brpop as can be seen at https://github.com/mmacedoeu/csvtoredis.rs/blob/master/src/main.rs

```
		let pop = try!(con.brpop(REQUEST_KEY, TIMEOUT));
		println!("{:?}", pop);
```
Prepopulating the REQUEST_KEY or at runtime println always print '()'.
I could see the set is consumed but couldnt see it on display.

Still i didnt figure out how to match pop so I parse only non empty demands.

**Comment by mitsuhiko** [comment]
I'm surprised you can do that at all. Maybe they finally implemented defaults?

In any case you want this:

```rust
let pop : String = try!(cno.brpop(REQUEST_KEY, TIMEOUT));
```

**Comment by mmacedoeu** [comment]
Looks like the response is some kind of Bulk or Iterator:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Response was of incompatible type: "Response type not string compatible." (response was bulk(string-data('"csv.req"'), string-data('"s;test"')))', ../src/libcore/result.rs:736
```

**Comment by mitsuhiko** [comment]
Ah yep. Do this then:

```rust
let (key, item) : (String, String) = try!(con.brpop(REQUEST_KEY, TIMEOUT));
```

**Comment by mmacedoeu** [comment]
Now It could handle handle non empty sets, but when the brpop timeout it panics with 

```
"s;test"
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Response was of incompatible type: "Not a bulk response" (response was nil)', ../src/libcore/result.rs:736
```

**Comment by mitsuhiko** [comment]
Sorry, but this is not a support forum. This error is not even specific to redis, it's just a type cast error.  Make it an `Option<(String, String)>` then.

**Comment by mitsuhiko** [comment]
The type handling is documented here: http://mitsuhiko.github.io/redis-rs/redis/#type-conversions
