### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by mroth** [mitsuhiko/redis-rs#81]
I just created a comparison using this library with @stefanwille's redis-client-benchmarks:
https://github.com/stefanwille/redis-client-benchmarks/pull/5

I was surprised to see the not only the Crystal implementation, but more notably the Go implementation seemed to be significantly faster (about 2x at least in this particular micro benchmark):

```
ruby_redisrb_hiredis_performance.rb  4.99s user 0.24s system 89% cpu 5.856 total
go_redigo_performance                0.38s user 0.04s system 43% cpu 0.973 total
crystal_redis_performance            0.37s user 0.08s system 44% cpu 0.993 total
rust-redis-client-performance        1.21s user 0.11s system 61% cpu 2.146 total
```

I would appreciate any feedback on the way I implemented the benchmark.  E.g. is this a case of potential profiling work that could be done to improve the performance this library, or am I perhaps misunderstanding something?

**Comment by mitsuhiko** [comment]
The library is very inefficient at parsing. I would love to get patches for improving it, but it's good enough for my purposes and my time is limited.

**Comment by NicolasLM** [comment]
A quick win could be to optionally use hiredis for parsing. Most redis clients have two parsers: the (slow) native one and the fast one based on hiredis.

See for instance https://github.com/andymccurdy/redis-py#parsers

**Comment by mitsuhiko** [comment]
My naive assumption is that it's not slow because of the parsing but because of how it consumes the input stream of bytes. I think if someone wants to look at this it would make sense to quickly add some timers and see where it's slow.

**Comment by badboy** [comment]
Nope, please not include hiredis here. It will cause more trouble than it will improve speed (speaking as maintainer of hiredis)

**Comment by gsquire** [comment]
As a learning experience, I am playing around with [nom](https://github.com/Geal/nom) and making a parser for the RESP. If you are ok with bringing this in as a dependency, I can make a PR in a short while. This may help with the parsing times.

**Comment by badboy** [comment]
The parser has seen lots of improvements. I don't have benchmarks against other libraries, but I think this should be less of an issue now.
