### ISSUE TITLE
Can support u128 for redis::Script arg?

### ISSUE THREAD

**Issue by matrixcloud** [mitsuhiko/redis-rs#819]
Here is the scenario, I tried to put a timestamp (nanoseconds) as script arg.

```rust
let now = time::SystemTime::now()
            .duration_since(time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
redis::Script::new("").arg(now)
```

Add the following code to types?

```
itoa_based_to_redis_impl!(u128, NumericBehavior::NumberIsInteger);
```

**Comment by jaymell** [comment]
Want to raise a PR?

**Comment by matrixcloud** [comment]
> Want to raise a PR?

sure 😊

**Comment by DoumanAsh** [comment]
Just for reference neither redis or lua support 128 bit integers, so you're likely need to truncate it to maximum of `u64::max_value()`

**Comment by jaymell** [comment]
> Just for reference neither redis nor lua support 128 bit integers, 

Yes, which is why I've unfortunately sat on #825  :sweat: I think in 99% of cases, what @matrixcloud  wants to do here is totally fine, as it will be stored in redis as a string anyway, but I'm not entirely clear of the potential for bad outcomes in other scenarios.

**Comment by DoumanAsh** [comment]
If it is store as string rather than integer it is ok.
String interpretation is up to library and redis gives zero shit about content of it.
So it is fully fine as long as you communicate to user that integers are stored as strings

**Comment by matrixcloud** [comment]
> If it is store as string rather than integer it is ok. String interpretation is up to library and redis gives zero shit about content of it. So it is fully fine as long as you communicate to user that integers are stored as strings

@DoumanAsh Yes, thanks point that out. String is a better option rather than truncating it to maximum of `u64::max_value()`

There an error will be thrown if value is exceeded once execute `incr`

```
127.0.0.1:6379> set value 9223372036854775807
OK
127.0.0.1:6379> incr value
(error) ERR increment or decrement would overflow
```
