### ISSUE TITLE
Handling BULK responses

### ISSUE THREAD

**Issue by andrey-gvrd** [mitsuhiko/redis-rs#82]
I'm trying to parse a response from `HGETALL` command:

    let res: redis::RedisResult<String> = redis::cmd("HGETALL").arg(key.clone()).query(&con);

But this fails at run-time with:

    Response was of incompatible type: "Response type not string compatible." (response was bulk(string-data('"some_string"'), string-data('"other_string"')))

I've tried replacing the `String` type with `<redis::types::Value as Trait>::Bulk`, but couldn't get it to compile. What is the right way to do this?

**Comment by badboy** [comment]
`HGETALL` gives you a list of fields and values. You need to collect that into a `Vec<String>`
