### ISSUE TITLE
Wrong number of arguments when using mget with redis-rs

### ISSUE THREAD

**Issue by cristianmedeiros** [mitsuhiko/redis-rs#95]
I'm trying to access Redis using Rust with the following:

```
extern crate redis;

use redis::{Client, Commands, Connection, RedisResult};

fn main() {

    let redis_client = Client::open("redis://127.0.0.1/").unwrap();
    let redis_conn = redis_client.get_connection().unwrap();

    let mut keys_to_get = vec![];
    keys_to_get.push("random_key_1".to_string());
    keys_to_get.push("random_key_2".to_string());
    let redis_result: String = redis_conn.get(keys_to_get).unwrap();
}
```
When I run `cargo run` I get:

```
     Running `target/debug/test_resdis`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: An error was signalled by the server: wrong number of arguments for 'get' command', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target/debug/test_resdis` (exit code: 101)
```

As explained in [this answer](http://stackoverflow.com/a/38015201/244203) Under the hood, the library inspects the key type to know if it's multivalued or not, using `ToRedisArgs::is_single_arg`, which has a default implementation of true.

I'm trying to do a PR, but still too newbie in Rust to success :( 

I will keep trying, but I'd like to let the bug(?) filled.

**Comment by mitsuhiko** [comment]
Not sure why that picks up the default implementation. There is an implementation for vectors that checks the size. I will have a look at that.

**Comment by badboy** [comment]
There is not: https://github.com/mitsuhiko/redis-rs/blob/master/src/types.rs#L518-L522
It only defines `to_redis_args`, but not `is_single_arg`. Using the same implementation for `is_single_arg` as the one for `&[T]` fixes this.

**Comment by mitsuhiko** [comment]
Indeed. That's an easy fix then.
