### ISSUE TITLE
Use Features for rustc_serialize and serde

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/redis-rs#96]
Since `rustc_serialize` is on the way out and serde is kinda on the way in, it would be great to make those optional dependencies.

**Comment by badboy** [comment]
As we are only using this for (de)serializing arguments/the result of commands, it is pretty easy to switch out: https://github.com/mitsuhiko/redis-rs/commit/bc89eaf1f813c38626d31fd0d762ba39614c40ce

**Comment by mitsuhiko** [comment]
Damn. Just saw your commit. I just moved rustc-serialize behind a feature now. No point in adding serde support, it's easier to just invoke a `serde_json::from_str` manually.

**Comment by badboy** [comment]
:+1: fine with me

**Comment by Boscop** [comment]
Does it mean this crate already supports any custom type that impls `Serialize` and `Deserialize` now?

If now, could it be added with `serde_json`?

**Comment by mitsuhiko** [comment]
@Boscop if you mean if we automatically serialize to json in and out, the answer is no. It's generally quite easy to do this manually. I'm not sure if automatic support makes sense here for doing this.
