### ISSUE TITLE
"make test" doesn't work under freebsd

### ISSUE THREAD

**Issue by letitberandom** [mitsuhiko/redis-rs#99]
[ ~/redis-rs]$ make test
make: exec(./runtests.sh) failed (No such file or directory)
**\* Error code 1

Stop.
make: stopped in /usr/home/user/redis-rs
[~/redis-rs]$ head -1 ./runtests.sh
# !/bin/bash

[ ~/redis-rs]$ which bash
/usr/local/bin/bash

**Comment by mitsuhiko** [comment]
I rather change it so that it does not need bash to run the tests
